// Plain-text document builder — no external deps

const WIDE = '═'.repeat(68)
const THIN = '─'.repeat(68)

function center(text: string, width = 68): string {
  const pad = Math.max(0, Math.floor((width - text.length) / 2))
  return ' '.repeat(pad) + text
}

function header(orgName: string, subtitle: string): string {
  return [
    WIDE,
    center(orgName),
    center('Generated by ChurchGPT · Church OS'),
    THIN,
    center(subtitle),
    WIDE,
    '',
  ].join('\n')
}

function meta(label: string, value: string): string {
  return value ? `${label.padEnd(22)}: ${value}` : ''
}

function section(title: string): string {
  return `\n${THIN}\n  ${title.toUpperCase()}\n${THIN}\n`
}

function bodyText(text: string): string {
  if (!text) return ''
  const words = text.split(' ')
  const lines: string[] = []
  let current = ''
  for (const word of words) {
    if (current.length + word.length + 1 > 68) {
      lines.push(current)
      current = word
    } else {
      current = current ? `${current} ${word}` : word
    }
  }
  if (current) lines.push(current)
  return lines.join('\n')
}

function bullet(text: string): string {
  return `  • ${text}`
}

function callout(text: string): string {
  return text ? `  | ${text.trim().replace(/\n/g, '\n  | ')}` : ''
}

function footer(date: string): string {
  return `\n${WIDE}\n${center(`ChurchGPT · Church OS · ${date} · Confidential`)}\n${WIDE}`
}

// ── Document builders ─────────────────────────────────────────────────────────

function buildSermonOutlineTXT(d: Record<string, unknown>, orgName: string, date: string): string {
  const points = Array.isArray(d.main_points) ? d.main_points as Record<string, unknown>[] : []
  const illustrations = Array.isArray(d.illustrations) ? d.illustrations as string[] : []
  const lines: string[] = [
    header(orgName, String(d.title ?? 'Sermon Outline')),
    meta('Scripture', String(d.anchor_text ?? '')),
    meta('Big Idea', String(d.big_idea ?? '')),
    meta('Context', String(d.context ?? '')),
    section('Main Points'),
    ...points.flatMap((pt, i) => [
      `${i + 1}. ${String(pt.title ?? '')}`,
      bodyText(String(pt.content ?? '')),
      callout(String(pt.scripture ?? '')),
      '',
    ]),
    section('Illustrations & Stories'),
    ...illustrations.map(ill => bullet(ill)),
    section('Application'),
    bodyText(String(d.application ?? '')),
    section('Invitation / Altar Call'),
    callout(String(d.invitation ?? '')),
    footer(date),
  ]
  return lines.filter(l => l !== null && l !== undefined).join('\n')
}

function buildServiceOrderTXT(d: Record<string, unknown>, orgName: string, date: string): string {
  const items = Array.isArray(d.order_items) ? d.order_items as Record<string, unknown>[] : []
  const team = Array.isArray(d.team) ? d.team as Record<string, unknown>[] : []
  const lines: string[] = [
    header(orgName, String(d.title ?? 'Service Order')),
    meta('Date / Time', String(d.date_time ?? '')),
    meta('Theme', String(d.theme ?? '')),
    meta('Scripture Focus', String(d.scripture_focus ?? '')),
    section('Order of Service'),
    ...items.map(item =>
      `  ${String(item.time ?? '').padEnd(10)} ${String(item.element ?? '')}${item.leader ? ` (${String(item.leader)})` : ''}`
    ),
    section('Team Assignments'),
    ...team.map(t => meta(String(t.role ?? ''), String(t.name ?? ''))),
    section('Notes'),
    bodyText(String(d.notes ?? '')),
    footer(date),
  ]
  return lines.join('\n')
}

function buildEventBriefTXT(d: Record<string, unknown>, orgName: string, date: string): string {
  const timeline = Array.isArray(d.timeline) ? d.timeline as Record<string, unknown>[] : []
  const checklist = Array.isArray(d.checklist) ? d.checklist as string[] : []
  const lines: string[] = [
    header(orgName, String(d.title ?? 'Event Brief')),
    meta('Event Date', String(d.event_date ?? '')),
    meta('Venue', String(d.venue ?? '')),
    meta('Expected Attendance', String(d.expected_attendance ?? '')),
    meta('Budget', String(d.budget ?? '')),
    meta('Theme', String(d.theme ?? '')),
    meta('Objective', String(d.objective ?? '')),
    section('Timeline'),
    ...timeline.map(t => `  ${String(t.time ?? '').padEnd(10)} ${String(t.activity ?? '')}`),
    section('Team Roles'),
    bodyText(String(d.team_roles ?? '')),
    section('Pre-Event Checklist'),
    ...checklist.map(c => bullet(c)),
    section('Communications Plan'),
    bodyText(String(d.communications ?? '')),
    footer(date),
  ]
  return lines.join('\n')
}

function buildStewardshipCampaignTXT(d: Record<string, unknown>, orgName: string, date: string): string {
  const phases = Array.isArray(d.phases) ? d.phases as Record<string, unknown>[] : []
  const scriptures = Array.isArray(d.scriptures) ? d.scriptures as string[] : []
  const lines: string[] = [
    header(orgName, String(d.title ?? 'Stewardship Campaign')),
    meta('Goal', String(d.goal ?? '')),
    meta('Duration', String(d.duration ?? '')),
    meta('Tagline', String(d.tagline ?? '')),
    section('Campaign Overview'),
    bodyText(String(d.overview ?? '')),
    section('Phases'),
    ...phases.flatMap((ph, i) => [
      `  Phase ${i + 1}: ${String(ph.name ?? '')}`,
      bodyText(String(ph.description ?? '')),
      '',
    ]),
    section('Key Scriptures'),
    ...scriptures.map(s => callout(s)),
    section('Pastoral Appeal'),
    callout(String(d.pastoral_appeal ?? '')),
    section('Communications Strategy'),
    bodyText(String(d.communications ?? '')),
    footer(date),
  ]
  return lines.join('\n')
}

function buildBibleStudyGuideTXT(d: Record<string, unknown>, orgName: string, date: string): string {
  const questions = Array.isArray(d.discussion_questions) ? d.discussion_questions as Record<string, unknown>[] : []
  const lines: string[] = [
    header(orgName, String(d.title ?? 'Bible Study Guide')),
    meta('Passage', String(d.passage ?? '')),
    meta('Session', String(d.session_number ?? '')),
    meta('Theme', String(d.theme ?? '')),
    section('Introduction'),
    bodyText(String(d.introduction ?? '')),
    section('Context & Background'),
    bodyText(String(d.context ?? '')),
    section('Key Verse'),
    callout(String(d.key_verse ?? '')),
    section('Discussion Questions'),
    ...questions.flatMap((q, i) => [
      `  Q${i + 1}. ${String(q.question ?? '')}`,
      `       ${String(q.notes ?? '')}`,
      '',
    ]),
    section('Application'),
    bodyText(String(d.application ?? '')),
    section('Prayer'),
    callout(String(d.prayer ?? '')),
    footer(date),
  ]
  return lines.join('\n')
}

function buildSmallGroupGuideTXT(d: Record<string, unknown>, orgName: string, date: string): string {
  const questions = Array.isArray(d.discussion_questions) ? d.discussion_questions as Record<string, unknown>[] : []
  const activities = Array.isArray(d.activities) ? d.activities as string[] : []
  const lines: string[] = [
    header(orgName, String(d.title ?? 'Small Group Guide')),
    meta('Week', String(d.week ?? '')),
    meta('Theme', String(d.theme ?? '')),
    meta('Scripture', String(d.scripture ?? '')),
    section('Icebreaker'),
    bodyText(String(d.icebreaker ?? '')),
    section('Teaching Summary'),
    bodyText(String(d.teaching_summary ?? '')),
    section('Discussion Questions'),
    ...questions.flatMap((q, i) => [
      `  ${i + 1}. ${String(q.question ?? '')}`,
      `     ${String(q.notes ?? '')}`,
      '',
    ]),
    section('Activities'),
    ...activities.map(a => bullet(a)),
    section('Prayer Points'),
    bodyText(String(d.prayer_points ?? '')),
    section('Take-Home Challenge'),
    callout(String(d.take_home ?? '')),
    footer(date),
  ]
  return lines.join('\n')
}

function buildYouthLessonTXT(d: Record<string, unknown>, orgName: string, date: string): string {
  const activities = Array.isArray(d.activities) ? d.activities as Record<string, unknown>[] : []
  const takeaways = Array.isArray(d.takeaways) ? d.takeaways as string[] : []
  const lines: string[] = [
    header(orgName, String(d.title ?? 'Youth Lesson')),
    meta('Age Group', String(d.age_group ?? '')),
    meta('Scripture', String(d.scripture ?? '')),
    meta('Theme', String(d.theme ?? '')),
    meta('Duration', String(d.duration ?? '')),
    section('Objective'),
    bodyText(String(d.objective ?? '')),
    section('Hook / Opener'),
    bodyText(String(d.hook ?? '')),
    section('Core Teaching'),
    bodyText(String(d.core_teaching ?? '')),
    callout(String(d.key_verse ?? '')),
    section('Activities'),
    ...activities.flatMap(a => [
      `  ${String(a.name ?? '')} (${String(a.duration ?? '')})`,
      bodyText(String(a.description ?? '')),
      '',
    ]),
    section('Key Takeaways'),
    ...takeaways.map(t => bullet(t)),
    section('Parent Note'),
    bodyText(String(d.parent_note ?? '')),
    footer(date),
  ]
  return lines.join('\n')
}

function buildAdminDocumentTXT(d: Record<string, unknown>, orgName: string, date: string): string {
  const sections = Array.isArray(d.sections) ? d.sections as Record<string, unknown>[] : []
  const lines: string[] = [
    header(orgName, String(d.title ?? 'Document')),
    meta('Date', String(d.date ?? date)),
    meta('Author', String(d.author ?? '')),
    meta('Reference', String(d.reference ?? '')),
    '',
    bodyText(String(d.summary ?? '')),
    ...sections.flatMap(sec => [
      section(String(sec.heading ?? '')),
      bodyText(String(sec.content ?? '')),
    ]),
    footer(date),
  ]
  return lines.join('\n')
}

// ── Public API ────────────────────────────────────────────────────────────────

export function buildTXT(documentData: Record<string, unknown>, orgName = 'Church OS'): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const type = String(documentData.type ?? '')

  switch (type) {
    case 'sermon-outline':        return buildSermonOutlineTXT(documentData, orgName, date)
    case 'service-order':         return buildServiceOrderTXT(documentData, orgName, date)
    case 'event-brief':           return buildEventBriefTXT(documentData, orgName, date)
    case 'stewardship-campaign':  return buildStewardshipCampaignTXT(documentData, orgName, date)
    case 'bible-study-guide':     return buildBibleStudyGuideTXT(documentData, orgName, date)
    case 'small-group-guide':     return buildSmallGroupGuideTXT(documentData, orgName, date)
    case 'youth-lesson':          return buildYouthLessonTXT(documentData, orgName, date)
    default:                      return buildAdminDocumentTXT(documentData, orgName, date)
  }
}
