import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  VerticalAlign,
  WidthType,
} from 'docx'

// ── Brand colours (used as hex strings) ──────────────────────────────────────
const NAVY  = '0F1F3D'
const GOLD  = 'D4AF37'
const LIGHT = 'F5F3EE'
const WHITE = 'FFFFFF'

// ── Shared helpers ────────────────────────────────────────────────────────────

function gap(lines = 1): Paragraph[] {
  return Array.from({ length: lines }, () =>
    new Paragraph({ children: [new TextRun('')], spacing: { after: 0 } })
  )
}

function rule(): Paragraph {
  return new Paragraph({
    border: { bottom: { color: GOLD, size: 6, space: 4, style: BorderStyle.SINGLE } },
    spacing: { after: 120 },
    children: [],
  })
}

function orgHeader(orgName: string): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
    children: [
      new TextRun({
        text: orgName,
        bold: true,
        size: 22,
        color: NAVY,
        font: 'Calibri',
      }),
    ],
  })
}

function poweredBy(): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
    children: [
      new TextRun({
        text: 'Generated by ChurchGPT · Church OS',
        size: 16,
        color: GOLD,
        italics: true,
        font: 'Calibri',
      }),
    ],
  })
}

function docTitle(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    alignment: AlignmentType.CENTER,
    shading: { type: ShadingType.SOLID, color: NAVY, fill: NAVY },
    spacing: { before: 200, after: 200 },
    children: [
      new TextRun({
        text,
        bold: true,
        size: 32,
        color: WHITE,
        font: 'Calibri',
      }),
    ],
  })
}

function metaLine(label: string, value: string): Paragraph {
  return new Paragraph({
    spacing: { after: 80 },
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 20, color: NAVY, font: 'Calibri' }),
      new TextRun({ text: value, size: 20, color: '444444', font: 'Calibri' }),
    ],
  })
}

function sectionLabel(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    shading: { type: ShadingType.SOLID, color: '1E3A5F', fill: '1E3A5F' },
    spacing: { before: 240, after: 120 },
    children: [
      new TextRun({ text: text.toUpperCase(), bold: true, size: 24, color: GOLD, font: 'Calibri' }),
    ],
  })
}

function bodyPara(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: [
      new TextRun({ text, size: 20, color: '333333', font: 'Calibri' }),
    ],
  })
}

function bullet(text: string, level = 0): Paragraph {
  return new Paragraph({
    bullet: { level },
    spacing: { after: 80 },
    children: [
      new TextRun({ text, size: 20, color: '333333', font: 'Calibri' }),
    ],
  })
}

function callout(text: string): Paragraph {
  return new Paragraph({
    shading: { type: ShadingType.SOLID, color: 'FBF6E6', fill: 'FBF6E6' },
    border: {
      left: { color: GOLD, size: 12, space: 6, style: BorderStyle.SINGLE },
    },
    spacing: { before: 80, after: 120 },
    indent: { left: 200 },
    children: [
      new TextRun({ text, italics: true, size: 20, color: '5C4500', font: 'Georgia' }),
    ],
  })
}

function invitationCallout(text: string): Paragraph {
  return new Paragraph({
    shading: { type: ShadingType.SOLID, color: LIGHT, fill: LIGHT },
    alignment: AlignmentType.CENTER,
    spacing: { before: 120, after: 120 },
    children: [
      new TextRun({ text, bold: true, italics: true, size: 22, color: NAVY, font: 'Georgia' }),
    ],
  })
}

function docFooter(date: string): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    border: { top: { color: GOLD, size: 4, space: 4, style: BorderStyle.SINGLE } },
    spacing: { before: 400 },
    children: [
      new TextRun({
        text: `ChurchGPT — Church OS · ${date} · Confidential`,
        size: 16,
        color: '888888',
        font: 'Calibri',
      }),
    ],
  })
}

function makeDocument(children: Paragraph[]): Document {
  return new Document({
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 20, color: '333333' },
        },
      },
    },
    sections: [{ properties: {}, children }],
  })
}

// ── Document builders ─────────────────────────────────────────────────────────

function buildSermonOutline(d: Record<string, unknown>, orgName: string, date: string): Paragraph[] {
  const points = Array.isArray(d.main_points) ? d.main_points as Record<string, unknown>[] : []
  const illustrations = Array.isArray(d.illustrations) ? d.illustrations as string[] : []
  return [
    orgHeader(orgName), poweredBy(), docTitle(String(d.title ?? 'Sermon Outline')),
    ...gap(),
    metaLine('Scripture', String(d.anchor_text ?? '')),
    metaLine('Big Idea', String(d.big_idea ?? '')),
    metaLine('Context', String(d.context ?? '')),
    rule(),
    sectionLabel('Main Points'),
    ...points.flatMap((pt, i) => [
      new Paragraph({
        spacing: { before: 160, after: 80 },
        children: [
          new TextRun({ text: `${i + 1}. ${String(pt.title ?? '')}`, bold: true, size: 22, color: NAVY, font: 'Calibri' }),
        ],
      }),
      bodyPara(String(pt.content ?? '')),
      callout(String(pt.scripture ?? '')),
    ]),
    rule(),
    sectionLabel('Illustrations & Stories'),
    ...illustrations.map(ill => bullet(ill)),
    rule(),
    sectionLabel('Application'),
    bodyPara(String(d.application ?? '')),
    rule(),
    sectionLabel('Invitation / Altar Call'),
    invitationCallout(String(d.invitation ?? '')),
    ...gap(2),
    docFooter(date),
  ]
}

function buildServiceOrder(d: Record<string, unknown>, orgName: string, date: string): Paragraph[] {
  const items = Array.isArray(d.order_items) ? d.order_items as Record<string, unknown>[] : []
  const team = Array.isArray(d.team) ? d.team as Record<string, unknown>[] : []
  return [
    orgHeader(orgName), poweredBy(), docTitle(String(d.title ?? 'Service Order')),
    ...gap(),
    metaLine('Date / Time', String(d.date_time ?? '')),
    metaLine('Theme', String(d.theme ?? '')),
    metaLine('Scripture Focus', String(d.scripture_focus ?? '')),
    rule(),
    sectionLabel('Order of Service'),
    ...items.map(item =>
      new Paragraph({
        spacing: { after: 100 },
        children: [
          new TextRun({ text: `${String(item.time ?? '')}  `, bold: true, size: 20, color: NAVY, font: 'Calibri' }),
          new TextRun({ text: String(item.element ?? ''), size: 20, font: 'Calibri' }),
          item.leader ? new TextRun({ text: `  (${String(item.leader)})`, size: 18, color: '888888', italics: true, font: 'Calibri' }) : new TextRun(''),
        ],
      })
    ),
    rule(),
    sectionLabel('Team Assignments'),
    ...team.map(t => metaLine(String(t.role ?? ''), String(t.name ?? ''))),
    rule(),
    sectionLabel('Notes'),
    bodyPara(String(d.notes ?? '')),
    ...gap(2),
    docFooter(date),
  ]
}

function buildEventBrief(d: Record<string, unknown>, orgName: string, date: string): Paragraph[] {
  const timeline = Array.isArray(d.timeline) ? d.timeline as Record<string, unknown>[] : []
  const checklist = Array.isArray(d.checklist) ? d.checklist as string[] : []
  return [
    orgHeader(orgName), poweredBy(), docTitle(String(d.title ?? 'Event Brief')),
    ...gap(),
    metaLine('Event Date', String(d.event_date ?? '')),
    metaLine('Venue', String(d.venue ?? '')),
    metaLine('Expected Attendance', String(d.expected_attendance ?? '')),
    metaLine('Budget', String(d.budget ?? '')),
    metaLine('Theme', String(d.theme ?? '')),
    metaLine('Objective', String(d.objective ?? '')),
    rule(),
    sectionLabel('Timeline'),
    ...timeline.map(t =>
      new Paragraph({
        spacing: { after: 80 },
        children: [
          new TextRun({ text: `${String(t.time ?? '')}  `, bold: true, size: 20, color: NAVY, font: 'Calibri' }),
          new TextRun({ text: String(t.activity ?? ''), size: 20, font: 'Calibri' }),
        ],
      })
    ),
    rule(),
    sectionLabel('Team Roles'),
    bodyPara(String(d.team_roles ?? '')),
    rule(),
    sectionLabel('Pre-Event Checklist'),
    ...checklist.map(c => bullet(c)),
    rule(),
    sectionLabel('Communications Plan'),
    bodyPara(String(d.communications ?? '')),
    ...gap(2),
    docFooter(date),
  ]
}

function buildStewardshipCampaign(d: Record<string, unknown>, orgName: string, date: string): Paragraph[] {
  const phases = Array.isArray(d.phases) ? d.phases as Record<string, unknown>[] : []
  const scriptures = Array.isArray(d.scriptures) ? d.scriptures as string[] : []
  return [
    orgHeader(orgName), poweredBy(), docTitle(String(d.title ?? 'Stewardship Campaign')),
    ...gap(),
    metaLine('Goal', String(d.goal ?? '')),
    metaLine('Duration', String(d.duration ?? '')),
    metaLine('Tagline', String(d.tagline ?? '')),
    rule(),
    sectionLabel('Campaign Overview'),
    bodyPara(String(d.overview ?? '')),
    rule(),
    sectionLabel('Phases'),
    ...phases.flatMap((ph, i) => [
      new Paragraph({
        spacing: { before: 160, after: 80 },
        children: [
          new TextRun({ text: `Phase ${i + 1}: ${String(ph.name ?? '')}`, bold: true, size: 22, color: NAVY, font: 'Calibri' }),
        ],
      }),
      bodyPara(String(ph.description ?? '')),
    ]),
    rule(),
    sectionLabel('Key Scriptures'),
    ...scriptures.map(s => callout(s)),
    rule(),
    sectionLabel('Pastoral Appeal'),
    invitationCallout(String(d.pastoral_appeal ?? '')),
    rule(),
    sectionLabel('Communications Strategy'),
    bodyPara(String(d.communications ?? '')),
    ...gap(2),
    docFooter(date),
  ]
}

function buildBibleStudyGuide(d: Record<string, unknown>, orgName: string, date: string): Paragraph[] {
  const questions = Array.isArray(d.discussion_questions) ? d.discussion_questions as Record<string, unknown>[] : []
  return [
    orgHeader(orgName), poweredBy(), docTitle(String(d.title ?? 'Bible Study Guide')),
    ...gap(),
    metaLine('Passage', String(d.passage ?? '')),
    metaLine('Session', String(d.session_number ?? '')),
    metaLine('Theme', String(d.theme ?? '')),
    rule(),
    sectionLabel('Introduction'),
    bodyPara(String(d.introduction ?? '')),
    rule(),
    sectionLabel('Context & Background'),
    bodyPara(String(d.context ?? '')),
    rule(),
    sectionLabel('Key Verse'),
    callout(String(d.key_verse ?? '')),
    rule(),
    sectionLabel('Discussion Questions'),
    ...questions.flatMap((q, i) => [
      new Paragraph({
        spacing: { before: 120, after: 40 },
        children: [
          new TextRun({ text: `Q${i + 1}. ${String(q.question ?? '')}`, bold: true, size: 20, color: NAVY, font: 'Calibri' }),
        ],
      }),
      bodyPara(String(q.notes ?? '')),
    ]),
    rule(),
    sectionLabel('Application'),
    bodyPara(String(d.application ?? '')),
    rule(),
    sectionLabel('Prayer'),
    callout(String(d.prayer ?? '')),
    ...gap(2),
    docFooter(date),
  ]
}

function buildSmallGroupGuide(d: Record<string, unknown>, orgName: string, date: string): Paragraph[] {
  const questions = Array.isArray(d.discussion_questions) ? d.discussion_questions as Record<string, unknown>[] : []
  const activities = Array.isArray(d.activities) ? d.activities as string[] : []
  return [
    orgHeader(orgName), poweredBy(), docTitle(String(d.title ?? 'Small Group Guide')),
    ...gap(),
    metaLine('Week', String(d.week ?? '')),
    metaLine('Theme', String(d.theme ?? '')),
    metaLine('Scripture', String(d.scripture ?? '')),
    rule(),
    sectionLabel('Icebreaker'),
    bodyPara(String(d.icebreaker ?? '')),
    rule(),
    sectionLabel('Teaching Summary'),
    bodyPara(String(d.teaching_summary ?? '')),
    rule(),
    sectionLabel('Discussion Questions'),
    ...questions.flatMap((q, i) => [
      new Paragraph({
        spacing: { before: 120, after: 40 },
        children: [
          new TextRun({ text: `${i + 1}. ${String(q.question ?? '')}`, bold: true, size: 20, color: NAVY, font: 'Calibri' }),
        ],
      }),
      bodyPara(String(q.notes ?? '')),
    ]),
    rule(),
    sectionLabel('Activities'),
    ...activities.map(a => bullet(a)),
    rule(),
    sectionLabel('Prayer Points'),
    bodyPara(String(d.prayer_points ?? '')),
    rule(),
    sectionLabel('Take-Home Challenge'),
    invitationCallout(String(d.take_home ?? '')),
    ...gap(2),
    docFooter(date),
  ]
}

function buildYouthLesson(d: Record<string, unknown>, orgName: string, date: string): Paragraph[] {
  const activities = Array.isArray(d.activities) ? d.activities as Record<string, unknown>[] : []
  const takeaways = Array.isArray(d.takeaways) ? d.takeaways as string[] : []
  return [
    orgHeader(orgName), poweredBy(), docTitle(String(d.title ?? 'Youth Lesson')),
    ...gap(),
    metaLine('Age Group', String(d.age_group ?? '')),
    metaLine('Scripture', String(d.scripture ?? '')),
    metaLine('Theme', String(d.theme ?? '')),
    metaLine('Duration', String(d.duration ?? '')),
    rule(),
    sectionLabel('Objective'),
    bodyPara(String(d.objective ?? '')),
    rule(),
    sectionLabel('Hook / Opener'),
    bodyPara(String(d.hook ?? '')),
    rule(),
    sectionLabel('Core Teaching'),
    bodyPara(String(d.core_teaching ?? '')),
    callout(String(d.key_verse ?? '')),
    rule(),
    sectionLabel('Activities'),
    ...activities.flatMap(a => [
      new Paragraph({
        spacing: { before: 120, after: 40 },
        children: [
          new TextRun({ text: String(a.name ?? ''), bold: true, size: 20, color: NAVY, font: 'Calibri' }),
          new TextRun({ text: `  (${String(a.duration ?? '')})`, size: 18, color: '888888', font: 'Calibri' }),
        ],
      }),
      bodyPara(String(a.description ?? '')),
    ]),
    rule(),
    sectionLabel('Key Takeaways'),
    ...takeaways.map(t => bullet(t)),
    rule(),
    sectionLabel('Parent Note'),
    bodyPara(String(d.parent_note ?? '')),
    ...gap(2),
    docFooter(date),
  ]
}

function buildAdminDocument(d: Record<string, unknown>, orgName: string, date: string): Paragraph[] {
  const sections = Array.isArray(d.sections) ? d.sections as Record<string, unknown>[] : []
  return [
    orgHeader(orgName), poweredBy(), docTitle(String(d.title ?? 'Document')),
    ...gap(),
    metaLine('Date', String(d.date ?? date)),
    metaLine('Author', String(d.author ?? '')),
    metaLine('Reference', String(d.reference ?? '')),
    rule(),
    bodyPara(String(d.summary ?? '')),
    ...sections.flatMap(sec => [
      rule(),
      sectionLabel(String(sec.heading ?? '')),
      bodyPara(String(sec.content ?? '')),
    ]),
    ...gap(2),
    docFooter(date),
  ]
}

// ── Public API ────────────────────────────────────────────────────────────────

export async function buildDocx(
  documentData: Record<string, unknown>,
  orgName = 'Church OS'
): Promise<Buffer> {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const type = String(documentData.type ?? '')

  let children: Paragraph[]
  switch (type) {
    case 'sermon-outline':        children = buildSermonOutline(documentData, orgName, date); break
    case 'service-order':         children = buildServiceOrder(documentData, orgName, date); break
    case 'event-brief':           children = buildEventBrief(documentData, orgName, date); break
    case 'stewardship-campaign':  children = buildStewardshipCampaign(documentData, orgName, date); break
    case 'bible-study-guide':     children = buildBibleStudyGuide(documentData, orgName, date); break
    case 'small-group-guide':     children = buildSmallGroupGuide(documentData, orgName, date); break
    case 'youth-lesson':          children = buildYouthLesson(documentData, orgName, date); break
    default:                      children = buildAdminDocument(documentData, orgName, date); break
  }

  const doc = makeDocument(children)
  return Packer.toBuffer(doc) as unknown as Buffer
}
