
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

const csvData = `name,slug,denomination,category,country,city,address,pastor_name,website,phone,email,description,mission_statement,founding_year,member_count,ministry_count,is_church_os_client,is_verified,accepts_donations,donation_url
"Tokyo Union Church","tokyo-union-church-tokyo","Non-Denominational","non-denominational","Japan","Tokyo","5-7-7 Jingumae, Shibuya-ku, Tokyo, Japan","Pastor Steve Yamaguchi","https://tokyounion.org","+81 3 3400 0047","office@tokyounion.org","A historic international congregation in Tokyo providing a spiritual home for English speakers from many denominations.","To be a vibrant, inclusive Christian community in the heart of Tokyo.","1872","500","8","false","true","true","https://tokyounion.org/give"
"St. Ignatius Church","st-ignatius-church-tokyo","Catholic","catholic","Japan","Tokyo","6-5-1 Kojimachi, Chiyoda-ku, Tokyo, Japan","Fr. Ryuichiro Hanafusa","https://www.ignatius.gr.jp","+81 3 3263 4584","info@ignatius.gr.jp","One of the largest Catholic parishes in Tokyo, located near Sophia University and known for its diverse international masses.","A community of faith serving the local and international population.","1949","15000","15","false","true","true",null
"Mustard Seed Christian Church Osaka","mustard-seed-christian-church-osaka-osaka","Non-Denominational","non-denominational","Japan","Osaka","Osaka, Japan","Pastor Brandon Johnson","https://mustardseedosaka.com","+81 6 0000 0000","info@mustardseedosaka.com","A gospel-centered church plant in the heart of Osaka focused on reaching urban professionals and students.","To make disciples of Jesus Christ in Osaka.","2011","300","6","false","true","true","https://mustardseedosaka.com/give"
"Mustard Seed Christian Church Nagoya","mustard-seed-christian-church-nagoya-nagoya","Non-Denominational","non-denominational","Japan","Nagoya","Nagoya, Japan","Pastor Andy Boone","https://mustardseednagoya.com","+81 52 0000 0000","info@mustardseednagoya.com","A contemporary church in Nagoya known for its outreach to the local Japanese community and international residents.","Leading people to life in Christ.","2009","250","5","false","true","true","https://mustardseednagoya.com/give"
"Calvary Chapel Tokyo","calvary-chapel-tokyo-tokyo","Non-Denominational","non-denominational","Japan","Tokyo","Tokyo, Japan","Pastor Tommy","https://calvarychapeltokyo.org","+81 3 0000 0000","info@calvarychapeltokyo.org","A verse-by-verse teaching ministry in Tokyo focused on deep biblical study and fellowship.","Simply teaching the Word simply.","1995","200","4","false","true","true","https://calvarychapeltokyo.org/give"
"Tokyo Life Church","tokyo-life-church-tokyo","Non-Denominational","non-denominational","Japan","Tokyo","Tokyo, Japan","Pastor Derek","https://tokyolifechurch.com","+81 3 0000 0000","info@tokyolifechurch.com","A mission-focused church in Tokyo city that emphasizes community engagement and modern worship.","Life to the full in Tokyo.","2012","150","3","false","true","true",null
"Franciscan Chapel Center","franciscan-chapel-center-tokyo","Catholic","catholic","Japan","Tokyo","4-2-37 Roppongi, Minato-ku, Tokyo, Japan","Fr. Russ","https://franciscanchapelcentertokyo.org","+81 3 3401 2141","info@fcc.org","An English-language Catholic parish in the Roppongi district serving the diplomatic and expat community.","A sanctuary for the international community.","1967","2000","10","false","true","true",null
"Meguro Catholic Church","meguro-catholic-church-tokyo","Catholic","catholic","Japan","Tokyo","4-6-22 Kamiosaki, Shinagawa-ku, Tokyo, Japan","Fr. Leo","http://www.catholic-meguro.jp","+81 3 3491 5461","info@meguro-catholic.jp","A large Catholic parish in the Meguro area with a focus on education and social welfare.","Witnessing to Christ in the city.","1948","3000","8","false","true","true",null
"Azabu Franciscan Church","azabu-franciscan-church-tokyo","Catholic","catholic","Japan","Tokyo","3-21-25 Nishi-Azabu, Minato-ku, Tokyo, Japan","Fr. Michael","http://azabu-catholic.jp","+81 3 3408 1500","info@azabu-catholic.jp","A historic parish located in the Azabu district, known for its long tradition of service.","Faith through the Franciscan tradition.","1889","1000","5","false","true","true",null
"St. Alban's Anglican Church","st.-albans-anglican-church-tokyo","Anglican","anglican","Japan","Tokyo","3-6-25 Shiba-koen, Minato-ku, Tokyo, Japan","Rev. William","http://www.saintalbans.jp","+81 3 3431 8534","info@saintalbans.jp","The only English-speaking Anglican church in the Tokyo area, serving a multi-ethnic congregation.","A house of prayer for all people.","1956","300","4","false","true","true",null
"St. Paul's Catholic Church","st.-pauls-catholic-church-karuizawa","Catholic","catholic","Japan","Karuizawa","Karuizawa, Nagano, Japan","Fr. Kato","http://www.karuizawa-stpaul.org","+81 267 42 2429","info@stpaul.org","A beautiful wooden church in the resort town of Karuizawa, popular for weddings and summer services.","Grace in the mountains.","1935","500","3","false","true","true",null
"Karuizawa Shaw Memorial Church","karuizawa-shaw-memorial-church-karuizawa","Anglican","anglican","Japan","Karuizawa","Karuizawa, Nagano, Japan","Rev. Shaw","http://www.nskk.org","+81 267 42 0000","info@shaw.org","The oldest church in Karuizawa, founded by Alexander Croft Shaw, known as the father of the Karuizawa resort.","Legacy of faith and peace.","1895","100","2","false","true","true",null
"Matsugamine Catholic Church","matsugamine-catholic-church-utsunomiya","Catholic","catholic","Japan","Utsunomiya","Utsunomiya, Tochigi, Japan","Fr. Tanaka","http://www2.ucatv.ne.jp","+81 28 635 0405","info@matsugamine.jp","A landmark Catholic church in Utsunomiya featuring O谷 stone architecture.","Light of the world.","1932","600","4","false","true","true",null
"Nunoike Catholic Church","nunoike-catholic-church-nagoya","Catholic","catholic","Japan","Nagoya","Nagoya, Aichi, Japan","Bishop of Nagoya","http://www.nagoya.catholic.jp","+81 52 935 6305","info@nagoya.catholic.jp","The cathedral church of the Diocese of Nagoya, known for its twin spires.","Cathedral for the Nagoya region.","1962","1000","7","false","true","true",null
"Tajimi Catholic Church","tajimi-catholic-church-tajimi","Catholic","catholic","Japan","Tajimi","Tajimi, Gifu, Japan","Fr. SVD","http://www.svd-tajimi.jp","+81 572 22 1583","info@tajimi.jp","A monastery and parish known for its viticulture and historic stone building.","Rooted in the earth and spirit.","1930","400","4","false","true","true",null
"Catholic Himeji Church","catholic-himeji-church-himeji","Catholic","catholic","Japan","Himeji","Himeji, Hyogo, Japan","Fr. Peter","http://www.himeji.catholic.ne.jp","+81 79 222 2259","info@himeji.jp","A central Catholic community in Himeji city serving the local congregation near the castle.","Faith near the castle.","1950","700","5","false","true","true",null
"St. Michael's Cathedral","st.-michaels-cathedral-kobe","Anglican","anglican","Japan","Kobe","Kobe, Hyogo, Japan","Bishop of Kobe","http://www.kobe-cathedral.jp","+81 78 000 0000","info@kobe.jp","The cathedral church of the Anglican Diocese of Kobe, serving the Kansai region.","Gospel light in Kobe.","1881","500","5","false","true","true",null
"Yamaguchi Memorial Church","yamaguchi-memorial-church-yamaguchi","Catholic","catholic","Japan","Yamaguchi","Yamaguchi, Japan","Fr. Xavier","http://www.xavier.jp","+81 83 920 1549","info@xavier.jp","Commemorating the arrival of St. Francis Xavier in Yamaguchi, this church is a center of historical faith.","Xavier's mission continues.","1952","1000","6","false","true","true",null
"Hiroshima World Peace Memorial Cathedral","hiroshima-world-peace-memorial-cathedral-hiroshima","Catholic","catholic","Japan","Hiroshima","Hiroshima, Japan","Bishop of Hiroshima","http://www.hiroshima-catholic.jp","+81 82 221 0621","info@hiroshima.jp","A cathedral dedicated to global peace, built following the destruction of the atomic bomb.","Peace to the world.","1954","2000","10","false","true","true",null
"Catholic Yonago Church","catholic-yonago-church-yonago","Catholic","catholic","Japan","Yonago","Yonago, Tottori, Japan","Fr. Joseph","http://yonago.catholic.ne.jp","+81 859 22 3443","info@yonago.jp","A welcoming Catholic parish serving the Yonago community on the Sea of Japan coast.","Small church, big heart.","1955","200","3","false","true","true",null
"Tsuwano Catholic Church","tsuwano-catholic-church-tsuwano","Catholic","catholic","Japan","Tsuwano","Tsuwano, Shimane, Japan","Fr. Maria","http://tsuwano.ne.jp","+81 856 72 0438","info@tsuwano.jp","Known for its unique tatami-matted interior and history of Catholic persecution.","Remembering the martyrs.","1892","100","2","false","true","true",null
"Itoshima Catholic Church","itoshima-catholic-church-itoshima","Catholic","catholic","Japan","Itoshima","Itoshima, Fukuoka, Japan","Fr. Luke","http://itoshima.catholic.jp","+81 92 000 0000","info@itoshima.jp","A coastal parish in Fukuoka prefecture with a focus on local community evangelism.","Grace by the sea.","1960","150","2","false","true","true",null
"Nakatsu Catholic Church","nakatsu-catholic-church-nakatsu","Catholic","catholic","Japan","Nakatsu","Nakatsu, Oita, Japan","Fr. Paul","http://nakatsu.catholic.jp","+81 979 22 1215","info@nakatsu.jp","Serving the Nakatsu region with a focus on education and social assistance.","Faith in Oita.","1950","200","3","false","true","true",null
"Oita Catholic Church","oita-catholic-church-oita","Catholic","catholic","Japan","Oita","Oita, Japan","Fr. Andrew","http://oita.catholic.jp","+81 97 532 2306","info@oita.jp","The main Catholic community in Oita city, focused on parish fellowship.","One body in Christ.","1948","400","3","false","true","true",null
"Dozaki Church","dozaki-church-goto","Catholic","catholic","Japan","Goto","Goto, Nagasaki, Japan","Fr. Goto","http://goto.catholic.jp","+81 959 73 0705","info@goto.jp","A red-brick gothic church on the Goto islands, a symbol of the revival of Catholicism in Japan.","Gothic grace in Goto.","1908","300","4","false","true","true",null
"Sakitsu Church","sakitsu-church-amakusa","Catholic","catholic","Japan","Amakusa","Amakusa, Kumamoto, Japan","Fr. Amakusa","http://asakusa.catholic.jp","+81 969 78 6000","info@amakusa.jp","A gothic church in a traditional Japanese fishing village, part of the Hidden Christian UNESCO sites.","UNESCO site of faith.","1934","400","5","false","true","true",null
"Hirosaki Catholic Church","hirosaki-catholic-church-hirosaki","Catholic","catholic","Japan","Hirosaki","Hirosaki, Aomori, Japan","Fr. Thomas","http://hirosaki.catholic.jp","+81 172 33 0370","info@hirosaki.jp","A parish in the apple-growing region of Aomori with a strong community presence.","Faith in Aomori.","1910","300","3","false","true","true",null
"Catholic Noshiro Church","catholic-noshiro-church-noshiro","Catholic","catholic","Japan","Noshiro","Noshiro, Akita, Japan","Fr. Mark","http://noshiro.catholic.jp","+81 185 52 3550","info@noshiro.jp","A small but dedicated Catholic community in Akita prefecture.","Small light in the north.","1952","150","2","false","true","true",null
"Mototerakoji Cathedral","mototerakoji-cathedral-sendai","Catholic","catholic","Japan","Sendai","Sendai, Miyagi, Japan","Bishop of Sendai","http://sendai.catholic.jp","+81 22 222 5507","info@sendai.jp","The cathedral of the Diocese of Sendai, rebuilt after the 2011 disaster.","Hope for Tohoku.","1905","1200","6","false","true","true",null
"Kobe Union Church","kobe-union-church-kobe","Non-Denominational","non-denominational","Japan","Kobe","Kobe, Hyogo, Japan","Rev. Dave","http://www.kobeunionchurch.com","+81 78 000 0000","info@kobeunion.org","One of the oldest international churches in Japan, serving the diverse community of Kobe.","Serving the international community of Kobe.","1872","300","4","false","true","true","http://www.kobeunionchurch.com/give"
"Sacred Heart Cathedral","sacred-heart-cathedral-harare","Catholic","catholic","Zimbabwe","Harare","4th St, Harare, Zimbabwe","Fr. Robert","https://catholicchurch.org.zw","+263 24 000 0000","info@catholic.org.zw","The cathedral of the Roman Catholic Archdiocese of Harare, a prominent center of faith in the city.","Sanctuary for the capital.","1925","3000","10","false","true","true",null
"St. John's Cathedral","st.-johns-cathedral-bulawayo","Anglican","anglican","Zimbabwe","Bulawayo","Bulawayo, Zimbabwe","Bishop Cleophas","http://bulawayodiocese.org","+263 9 000 0000","info@bulawayo.org.zw","The historic Anglican cathedral of Bulawayo, known for its colonial architecture and music.","Beacon of hope in Bulawayo.","1910","1500","8","false","true","true",null
"Trinity Methodist Church","trinity-methodist-church-harare","Methodist","methodist","Zimbabwe","Harare","Harare, Zimbabwe","Rev. George","http://methodistchurch.org.zw","+263 24 000 0000","info@methodist.org.zw","A central Methodist congregation with a long history of social work and community development.","Social holiness in Harare.","1891","2000","7","false","true","true",null
"Central Baptist Church","central-baptist-church-bulawayo","Baptist","baptist","Zimbabwe","Bulawayo","Bulawayo, Zimbabwe","Pastor David","http://baptistzim.org","+263 9 000 0000","info@baptist.org.zw","A traditional Baptist church in Bulawayo focused on Bible teaching and missions.","Preaching the Word.","1950","1000","5","false","true","true",null
"Gweru Christian Centre","gweru-christian-centre-gweru","Pentecostal","pentecostal","Zimbabwe","Gweru","Gweru, Zimbabwe","Pastor M. Guti","https://fifmi.org","+263 54 000 0000","info@gweru.org.zw","A major hub for the ZAOGA FIF ministry in the Midlands province.","Kingdom life in the Midlands.","1975","5000","8","false","true","true",null
"Mutare Presbyterian Church","mutare-presbyterian-church-mutare","Presbyterian","presbyterian","Zimbabwe","Mutare","Mutare, Zimbabwe","Rev. S. Moyo","http://presbyterian.org.zw","+263 20 000 0000","info@mutare.org.zw","A historic Presbyterian congregation serving the community in the Eastern Highlands.","Preserving the Reformed faith.","1940","800","4","false","true","true",null
"PHD Ministries","phd-ministries-harare","Charismatic","charismatic","Zimbabwe","Harare","Waterfalls, Harare, Zimbabwe","Prophet Walter Magaya","http://phdministries.org","+263 24 000 0000","info@phd.org.zw","One of Zimbabwe's most popular prophetic ministries, attracting thousands to its weekly services.","Healing and deliverance for all.","2012","50000","15","false","true","true","http://phdministries.org/give"
"Salvation Ministries Harare","salvation-ministries-harare-harare","Pentecostal","pentecostal","Zimbabwe","Harare","Harare, Zimbabwe","Pastor David","http://salvationministries.org","+263 24 000 0000","info@salvation.org.zw","A vibrant branch of the international ministry focused on spiritual prosperity.","Spiritual growth in the city.","2010","5000","6","false","true","true",null
"Apostolic Faith Church Gweru","apostolic-faith-church-gweru-gweru","Apostolic","charismatic","Zimbabwe","Gweru","Gweru, Zimbabwe","Rev. Sibanda","http://afm.org.zw","+263 54 000 0000","info@afm.org.zw","A historic Pentecostal church with a deep foundation in the Midlands region.","Apostolic truth today.","1960","4000","6","false","true","true",null
"ZAOGA Mutare","zaoga-mutare-mutare","Pentecostal","pentecostal","Zimbabwe","Mutare","Mutare, Zimbabwe","Elder John","https://fifmi.org","+263 20 000 0000","info@mutare.org.zw","The main regional center for ZAOGA FIF in the eastern border city of Mutare.","Reaching Mutare for Christ.","1970","3000","6","false","true","true",null
"St. Mary and All Saints Mutare","st.-mary-and-all-saints-mutare-mutare","Anglican","anglican","Zimbabwe","Mutare","Mutare, Zimbabwe","Dean Mutamiri","http://anglicanmutare.org","+263 20 000 0000","info@anglican.org.zw","The Anglican cathedral of the Diocese of Manicaland, serving the eastern highlands.","Grace in the highlands.","1915","1200","5","false","true","true",null
"St. Theresa Cathedral","st.-theresa-cathedral-gweru","Catholic","catholic","Zimbabwe","Gweru","Gweru, Zimbabwe","Fr. Xavier","http://gwerucatholic.org","+263 54 000 0000","info@gweru.org.zw","The main Catholic cathedral in the Midlands, a center for education and healthcare missions.","Service in the Midlands.","1930","2500","7","false","true","true",null
"Masvingo Baptist Church","masvingo-baptist-church-masvingo","Baptist","baptist","Zimbabwe","Masvingo","Masvingo, Zimbabwe","Pastor Moyo","http://baptistzim.org","+263 39 000 0000","info@masvingo.org.zw","A long-standing Baptist presence in the historic city of Masvingo.","Bible truth in Masvingo.","1965","600","4","false","true","true",null
"Kwekwe Christian Centre","kwekwe-christian-centre-kwekwe","Pentecostal","pentecostal","Zimbabwe","Kwekwe","Kwekwe, Zimbabwe","Pastor Kwekwe","https://fifmi.org","+263 55 000 0000","info@kwekwe.org.zw","A community-focused church in the mining town of Kwekwe.","Faith in the heart of mining.","1980","2000","5","false","true","true",null
"Marondera Baptist Church","marondera-baptist-church-marondera","Baptist","baptist","Zimbabwe","Marondera","Marondera, Zimbabwe","Pastor Maro","http://baptistzim.org","+263 27 000 0000","info@marondera.org.zw","A growing Baptist congregation serving the Marondera agricultural hub.","Faith in the fields.","1970","500","3","false","true","true",null
"Chitungwiza Christian Centre","chitungwiza-christian-centre-chitungwiza","Pentecostal","pentecostal","Zimbabwe","Chitungwiza","Chitungwiza, Zimbabwe","Pastor Chit","https://fifmi.org","+263 24 000 0000","info@chitungwiza.org.zw","Serving the large dormitory town of Chitungwiza with vibrant services.","Community faith in Chitungwiza.","1985","4000","6","false","true","true",null
"Word of Life Harare","word-of-life-harare-harare","Pentecostal","pentecostal","Zimbabwe","Harare","Harare, Zimbabwe","Dr. Shana","https://wordoflife.co.zw","+263 24 000 0000","info@harare.org.zw","An urban congregation of Word of Life focused on leadership and growth.","Life in the word.","1995","3000","5","false","true","true","https://wordoflife.co.zw/give"
"Glad Tidings Bulawayo","glad-tidings-bulawayo-bulawayo","Pentecostal","pentecostal","Zimbabwe","Bulawayo","Bulawayo, Zimbabwe","Pastor G. Tidings","http://gladtidings.org.zw","+263 9 000 0000","info@bulawayo.org.zw","A welcoming fellowship in Bulawayo with a heart for the city.","Gladness in Bulawayo.","1988","2500","5","false","true","true",null
"Newfrontiers Harare","newfrontiers-harare-harare","Non-Denominational","non-denominational","Zimbabwe","Harare","Harare, Zimbabwe","Pastor Scott","http://riveroflife.co.zw","+263 24 000 0000","info@harare.org.zw","A modern, family-oriented church in Harare part of the Newfrontiers movement.","Building together.","1992","1500","4","false","true","true",null
"Christ Embassy Bulawayo","christ-embassy-bulawayo-bulawayo","Charismatic","charismatic","Zimbabwe","Bulawayo","Bulawayo, Zimbabwe","Pastor Chris","https://christembassy.org","+263 9 000 0000","info@bulawayo.org.zw","A dynamic charismatic ministry in Bulawayo focused on the message of grace.","Grace for Bulawayo.","1998","4000","6","false","true","true",null
"Durban Christian Centre","durban-christian-centre-durban","Pentecostal","pentecostal","South Africa","Durban","Jesus Dome, Mayville, Durban, South Africa","Pastor John Torrens","https://dcc.org.za","+27 31 000 0000","info@dcc.org.za","A major charismatic church in Durban known for its large 'Jesus Dome' and community missions.","Taking Jesus to the city.","1979","15000","15","false","true","true","https://dcc.org.za/give"
"Jubilee Community Church","jubilee-community-church-cape-town","Non-Denominational","non-denominational","South Africa","Cape Town","Cape Town, South Africa","Pastor Stephen Van Rhyn","https://jubilee.org.za","+27 21 000 0000","info@jubilee.org.za","A diverse community of believers in Cape Town with a heart for justice and worship.","For the glory of God and the good of the city.","1987","2000","8","false","true","true","https://jubilee.org.za/give"
"St. Mary's Cathedral Cape Town","st.-marys-cathedral-cape-town-cape-town","Catholic","catholic","South Africa","Cape Town","Roeland St, Cape Town, South Africa","Fr. Peter-John","https://stmaryscathedral.org.za","+27 21 000 0000","info@stmarys.org.za","The mother church of the Archdiocese of Cape Town, located near the Parliament.","Sanctuary for the Mother City.","1841","1500","6","false","true","true",null
"Northpoint City Church","northpoint-city-church-johannesburg","Non-Denominational","non-denominational","South Africa","Johannesburg","Johannesburg, South Africa","Pastor John","https://northpoint.org.za","+27 11 000 0000","info@northpoint.org.za","A growing community-focused church in Johannesburg.","Living for Christ in Jozi.","1995","2500","5","false","true","true",null
"Bryanston Bible Church","bryanston-bible-church-johannesburg","Non-Denominational","non-denominational","South Africa","Johannesburg","Johannesburg, South Africa","Pastor Blake","https://bbc.org.za","+27 11 000 0000","info@bbc.org.za","An evangelical, non-denominational church focused on gospel-centered living in the suburbs.","Gospel to the north.","1982","3000","7","false","true","true",null
"Gracepoint Methodist Church","gracepoint-methodist-church-johannesburg","Methodist","methodist","South Africa","Johannesburg","Johannesburg, South Africa","Rev. John","https://gracepoint.co.za","+27 11 000 0000","info@gracepoint.co.za","A modern Methodist congregation with a focus on grace and spiritual development.","Point of grace.","1990","4000","8","false","true","true","https://gracepoint.co.za/give"
"Christ Church Constantia","christ-church-constantia-cape-town","Anglican","anglican","South Africa","Cape Town","Cape Town, South Africa","Rev. Paul","http://christchurchconstantia.co.za","+27 21 000 0000","info@constantia.org.za","A historic Anglican parish in the Constantia valley.","Grace in the valley.","1834","800","4","false","true","true",null
"Constantia Catholic Church","constantia-catholic-church-cape-town","Catholic","catholic","South Africa","Cape Town","Cape Town, South Africa","Fr. Thomas","http://constantiacatholic.co.za","+27 21 000 0000","info@catholic.org.za","A local Catholic community serving the southern suburbs of Cape Town.","Sacramental life in Constantia.","1950","600","3","false","true","true",null
"Kingsway Church","kingsway-church-cape-town","Non-Denominational","non-denominational","South Africa","Cape Town","Cape Town, South Africa","Pastor King","https://kingsway.org.za","+27 21 000 0000","info@kingsway.org.za","A contemporary church in Cape Town focused on leadership and community.","Kingdom ways.","1992","1200","5","false","true","true",null
"West View Methodist Church","west-view-methodist-church-pretoria","Methodist","methodist","South Africa","Pretoria","Pretoria, South Africa","Rev. West","http://westview.org.za","+27 12 000 0000","info@westview.org.za","An active Methodist community in Pretoria with a heart for the city.","Faith in Pretoria.","1970","1500","6","false","true","true",null
"Midrand Chapel","midrand-chapel-midrand","Baptist","baptist","South Africa","Midrand","Midrand, South Africa","Pastor Mid","http://midrandchapel.co.za","+27 11 000 0000","info@midrand.org.za","An evangelical Baptist church serving the growing Midrand community.","Bible centered in Midrand.","1985","1000","4","false","true","true",null
"Sandton Bible Church","sandton-bible-church-sandton","Non-Denominational","non-denominational","South Africa","Sandton","Sandton, South Africa","Pastor Sand","http://sandtonbible.co.za","+27 11 000 0000","info@sandton.org.za","A biblical community in the business heart of South Africa.","Word in the city.","1980","2000","5","false","true","true",null
"Rosebank Catholic Church","rosebank-catholic-church-johannesburg","Catholic","catholic","South Africa","Johannesburg","Johannesburg, South Africa","Fr. Rose","http://rosebankcatholic.org.za","+27 11 000 0000","info@rosebank.org.za","A vibrant parish serving the Rosebank area.","Catholic faith in Jozi.","1935","1200","5","false","true","true",null
"Stellenbosch United Church","stellenbosch-united-church-stellenbosch","Non-Denominational","non-denominational","South Africa","Stellenbosch","Stellenbosch, South Africa","Rev. Stell","http://stclur.co.za","+27 21 000 0000","info@stclur.org.za","An English-speaking united congregation in the heart of Stellenbosch.","United in Christ.","1960","800","4","false","true","true",null
"Paarl Baptist Church","paarl-baptist-church-paarl","Baptist","baptist","South Africa","Paarl","Paarl, South Africa","Pastor Paarl","http://paarlbaptist.co.za","+27 21 000 0000","info@paarl.org.za","A local Baptist congregation in the Cape Winelands.","Truth in the winelands.","1945","700","3","false","true","true",null
"Somerset West Baptist","somerset-west-baptist-somerset-west","Baptist","baptist","South Africa","Somerset West","Somerset West, South Africa","Pastor Som","http://swbaptist.org.za","+27 21 000 0000","info@swbaptist.org.za","Serving the Somerset West community for over 70 years.","Gospel presence.","1950","900","4","false","true","true",null
"Knysna Methodist Church","knysna-methodist-church-knysna","Methodist","methodist","South Africa","Knysna","Knysna, South Africa","Rev. Kny","http://knysnamethodist.co.za","+27 44 000 0000","info@knysna.org.za","A coastal Methodist parish with a long history in the Garden Route.","Faith in Knysna.","1920","500","3","false","true","true",null
"Plettenberg Bay Christian Centre","plettenberg-bay-christian-centre-plettenberg-bay","Pentecostal","pentecostal","South Africa","Plettenberg Bay","Plettenberg Bay, South Africa","Pastor Plett","http://pbcc.co.za","+27 44 000 0000","info@pbcc.org.za","A charismatic community serving the Plett bay area.","Grace in the bay.","1988","600","3","false","true","true",null
"East London Baptist","east-london-baptist-east-london","Baptist","baptist","South Africa","East London","East London, South Africa","Pastor East","http://elbaptist.co.za","+27 43 000 0000","info@elbaptist.org.za","A traditional Baptist presence in the Buffalo City.","Bible truth in Buffalo City.","1910","1000","5","false","true","true",null
"Richards Bay Christian Centre","richards-bay-christian-centre-richards-bay","Pentecostal","pentecostal","South Africa","Richards Bay","Richards Bay, South Africa","Pastor Rich","http://rbcc.co.za","+27 35 000 0000","info@rbcc.org.za","Serving the industrial hub of Richards Bay with a charismatic focus.","Power in the port.","1985","2000","5","false","true","true",null
"Polokwane Christian Centre","polokwane-christian-centre-polokwane","Pentecostal","pentecostal","South Africa","Polokwane","Polokwane, South Africa","Pastor Pol","http://pcc.co.za","+27 15 000 0000","info@pcc.org.za","A leading Pentecostal church in the Limpopo province.","Limpopo light.","1990","3000","6","false","true","true",null
"Mbombela Family Church","mbombela-family-church-mbombela","Non-Denominational","non-denominational","South Africa","Mbombela","Mbombela, South Africa","Pastor Mbo","http://mbombela.co.za","+27 13 000 0000","info@mbo.org.za","A family-oriented church in the capital of Mpumalanga.","Family in the lowveld.","1992","1500","4","false","true","true",null
"Kimberley Baptist","kimberley-baptist-kimberley","Baptist","baptist","South Africa","Kimberley","Kimberley, South Africa","Pastor Kim","http://kimbaptist.co.za","+27 53 000 0000","info@kim.org.za","A historic Baptist church in the diamond city.","Truth in the city.","1905","800","3","false","true","true",null
"Welkom Christian Centre","welkom-christian-centre-welkom","Pentecostal","pentecostal","South Africa","Welkom","Welkom, South Africa","Pastor Wel","http://welkomcc.co.za","+27 57 000 0000","info@wel.org.za","Serving the mining community of Welkom.","Faith in the goldfields.","1980","2500","5","false","true","true",null
"NG Kerk Potchefstroom","ng-kerk-potchefstroom-potchefstroom","Reformed","reformed","South Africa","Potchefstroom","Potchefstroom, South Africa","Dominee Potch","http://ngkp.co.za","+27 18 000 0000","info@potch.org.za","One of the oldest Reformed congregations in the former Transvaal region.","Legacy of faith.","1842","5000","8","false","true","true",null
"Grahamstown Cathedral","grahamstown-cathedral-grahamstown","Anglican","anglican","South Africa","Grahamstown","Grahamstown, South Africa","Dean Graham","http://cathedral.org.za","+27 46 000 0000","info@graham.org.za","The historic Cathedral of St. Michael and St. George, a center for the Anglican Diocese of Grahamstown.","Cathedral for the city of saints.","1824","1000","6","false","true","true",null
"Umhlanga Rocks Catholic","umhlanga-rocks-catholic-umhlanga","Catholic","catholic","South Africa","Umhlanga","Umhlanga, South Africa","Fr. Rocks","http://urc.org.za","+27 31 000 0000","info@urc.org.za","A local Catholic parish serving the upscale coastal town of Umhlanga.","Faith by the rocks.","1965","1200","5","false","true","true",null
"Ballito Christian Church","ballito-christian-church-ballito","Non-Denominational","non-denominational","South Africa","Ballito","Ballito, South Africa","Pastor Ball","http://ballito.co.za","+27 32 000 0000","info@ballito.org.za","A contemporary community church on the north coast of KZN.","Wave of grace.","2000","1500","4","false","true","true",null
"Heritage Baptist Church","heritage-baptist-church-johannesburg","Baptist","baptist","South Africa","Johannesburg","Johannesburg, South Africa","Pastor Heri","http://heritagebaptist.co.za","+27 11 000 0000","info@heri.org.za","A Bible-based Baptist church in the south of Jozi.","Heritage of faith.","1998","500","3","false","true","true",null
"Antipas Reformed Baptist","antipas-reformed-baptist-pretoria","Baptist","baptist","South Africa","Pretoria","Pretoria, South Africa","Pastor Anti","http://antipas.co.za","+27 12 000 0000","info@anti.org.za","A Reformed Baptist church in Pretoria focused on theological depth.","Truth for the city.","2005","300","3","false","true","true",null
"Manchester Cathedral","manchester-cathedral-manchester","Anglican","anglican","United Kingdom","Manchester","Victoria St, Manchester, UK","Dean Rogers","https://manchestercathedral.org","+44 161 833 2220","office@manchestercathedral.org","A stunning gothic cathedral in the heart of Manchester, serving as a center of worship for over 600 years.","To grow and build a community that makes a difference.","1421","2000","12","false","true","true","https://manchestercathedral.org/give"
"St Martin in the Bull Ring","st-martin-in-the-bull-ring-birmingham","Anglican","anglican","United Kingdom","Birmingham","Bull Ring, Birmingham, UK","Rev. Jeremy Allcock","https://bullring.org","+44 121 643 5428","office@bullring.org","The original parish church of Birmingham, standing between the Bullring Shopping Centre and the markets.","A community of faith in the heart of the Bull Ring.","1263","1000","8","false","true","true",null
"Gas Street Church","gas-street-church-birmingham","Anglican","anglican","United Kingdom","Birmingham","41 Gas St, Birmingham, UK","Rev. Tim Hughes","https://gasstreet.church","+44 121 000 0000","info@gasstreet.org","A creative and vibrant Anglican community in a former gas works building, known for its worship music.","Light for the city.","2016","2500","10","false","true","true","https://gasstreet.church/give"
"St. Aldates","st-aldates-oxford","Anglican","anglican","United Kingdom","Oxford","Oxford, UK","Rev. Charlie Cleverly","https://staldates.org.uk","+44 1865 254800","info@staldates.org.uk","A large, lively Anglican church in central Oxford with a strong focus on student and young adult ministry.","Knowing God and making him known in Oxford.","1100","1500","12","false","true","true","https://staldates.org.uk/give"
"Highfield Church","highfield-church-southampton","Anglican","anglican","United Kingdom","Southampton","Southampton, UK","Rev. Mike","https://highfield.church","+44 23 8055 8234","info@highfield.church","An evangelical Anglican parish near the university serving students and the local community.","Faith, family, and future.","1847","800","6","false","true","true",null
"Charlotte Baptist Chapel","charlotte-baptist-chapel-edinburgh","Baptist","baptist","United Kingdom","Edinburgh","Edinburgh, Scotland, UK","Pastor Paul","https://charlottechapel.org","+44 131 225 4701","info@charlottechapel.org","A central Baptist church in Edinburgh with a strong evangelical and missionary focus.","Preaching Christ to the nations.","1808","1200","10","false","true","true",null
"St. George's Tron","st-georges-tron-glasgow","Presbyterian","presbyterian","United Kingdom","Glasgow","Glasgow, Scotland, UK","Rev. Alastair","https://thetron.org","+44 141 332 2795","info@thetron.org","A historic church in the center of Glasgow, focused on expositional Bible teaching.","Living the Gospel in Glasgow.","1807","1000","8","false","true","true",null
"Whitfield Tabernacle","whitfield-tabernacle-bristol","Methodist","methodist","United Kingdom","Bristol","Kingswood, Bristol, UK","Rev. George","http://whitfieldtabernacle.org","+44 117 000 0000","info@whitfield.org","A landmark in the history of Methodism, associated with George Whitefield.","Heritage of revival.","1741","300","3","false","true","true",null
"Above Bar Church","above-bar-church-southampton","Non-Denominational","non-denominational","United Kingdom","Southampton","Southampton, UK","Pastor Chris","https://abovebarchurch.org.uk","+44 23 8022 8275","info@abovebarchurch.org.uk","An independent evangelical church in Southampton with a passion for world mission and community outreach.","Following Jesus together.","1876","1200","8","false","true","true",null
"Christ Church Liverpool","christ-church-liverpool-liverpool","Anglican","anglican","United Kingdom","Liverpool","Liverpool, UK","Rev. Liver","http://ccl.org.uk","+44 151 000 0000","info@ccl.org.uk","An evangelical Anglican presence in Liverpool city center.","Hope for Liverpool.","1880","500","4","false","true","true",null
"Belfast City Church","belfast-city-church-belfast","Non-Denominational","non-denominational","United Kingdom","Belfast","Belfast, NI, UK","Pastor Bel","https://belfastcitychurch.com","+44 28 000 0000","info@belfastcity.org","A modern community church in Belfast focused on reconciliation and hope.","Belfast for Christ.","1985","1500","6","false","true","true",null
"Emmanuel Church Brighton","emmanuel-church-brighton-brighton","Non-Denominational","non-denominational","United Kingdom","Brighton","Brighton, UK","Pastor Joel","https://emmanuelbrighton.org.uk","+44 1273 000 0000","info@emmanuel.org.uk","A gospel-centered church on the south coast part of the Newfrontiers movement.","Gospel to the south.","1990","1000","5","false","true","true",null
"Trent Vineyard","trent-vineyard-nottingham","Non-Denominational","non-denominational","United Kingdom","Nottingham","Lenton Lane, Nottingham, UK","John Wright","https://trentvineyard.org","+44 115 988 7060","info@trentvineyard.org","A large, influential Vineyard church in Nottingham known for its worship and social action.","To be a vibrant community of faith.","1994","3000","12","false","true","true","https://trentvineyard.org/give"
"Kerith Community Church","kerith-community-church-bracknell","Non-Denominational","non-denominational","United Kingdom","Bracknell","Bracknell, UK","Simon Benham","https://kerith.church","+44 1344 862699","info@kerith.church","A multi-site church in the south-east of England focused on making followers of Jesus.","To help people know Jesus.","1982","2500","10","false","true","true","https://kerith.church/give"
"St. Peter's Brighton","st-peters-brighton-brighton","Anglican","anglican","United Kingdom","Brighton","Brighton, UK","Rev. Archie","https://stpetersbrighton.org","+44 1273 698182","info@stpetersbrighton.org","A revitalized Anglican parish in the center of Brighton part of the HTB network.","Revitalizing Brighton.","2009","1500","8","false","true","true",null
"Greyfriars Kirk","greyfriars-kirk-edinburgh","Presbyterian","presbyterian","United Kingdom","Edinburgh","Edinburgh, Scotland, UK","Rev. Richard","http://greyfriarskirk.com","+44 131 225 1900","info@greyfriarskirk.com","One of the oldest buildings in Edinburgh and a key site in the history of the Covenanters.","Faith in history.","1620","500","5","false","true","true",null
"St. Anne's Cathedral","st-annes-cathedral-belfast","Anglican","anglican","United Kingdom","Belfast","Belfast, NI, UK","Dean Stephen","http://belfastcathedral.org","+44 28 9032 8332","info@belfastcathedral.org","A Romanesque-style cathedral that serves as the heart of the Anglican community in Belfast.","Center for the city.","1899","1000","6","false","true","true",null
"Cardiff City Church","cardiff-city-church-cardiff","Pentecostal","pentecostal","United Kingdom","Cardiff","Cardiff, Wales, UK","Pastor Card","http://cardiffcitychurch.org","+44 29 2048 2058","info@cardiffcity.org","A dynamic Pentecostal church in the capital of Wales.","Cardiff for the Kingdom.","1980","1200","5","false","true","true",null
"Swansea City Temple","swansea-city-temple-swansea","Pentecostal","pentecostal","United Kingdom","Swansea","Swansea, Wales, UK","Pastor Swan","http://citytemple.net","+44 1792 654203","info@swansea.org","A long-established Pentecostal presence in the city of Swansea.","Legacy of faith in Wales.","1960","1000","5","false","true","true",null
"Canterbury Cathedral","canterbury-cathedral-canterbury","Anglican","anglican","United Kingdom","Canterbury","Canterbury, UK","Archbishop Justin Welby","https://canterbury-cathedral.org","+44 1227 762862","info@canterbury-cathedral.org","The mother church of the worldwide Anglican Communion and a UNESCO World Heritage site.","Seat of the Anglican world.","597","2000","15","false","true","true",null
"Nairobi Chapel","nairobi-chapel-nairobi","Evangelical","evangelical","Kenya","Nairobi","Ngong Rd, Nairobi, Kenya","Pastor Oscar Muriu","https://nairobichapel.org","+254 700 000 000","info@nairobichapel.org","A vibrant, multi-generational church in Nairobi focused on community transformation and leadership development.","To build a church for the city and a light for the nations.","1952","5000","12","false","true","true","https://nairobichapel.org/give"
"Watoto Church","watoto-church-kampala","Pentecostal","pentecostal","Uganda","Kampala","Kampala, Uganda","Pastor Gary Skinner","https://watotochurch.com","+256 000 0000","info@watoto.org","Formerly Kampala Pentecostal Church, Watoto is famous for its children's choir and community care for orphans.","To rescue a child, raise a leader, rebuild a nation.","1984","20000","15","false","true","true","https://watotochurch.com/give"
"House on the Rock","house-on-the-rock-lagos","Pentecostal","pentecostal","Nigeria","Lagos","Rock Cathedral, Lekki, Lagos, Nigeria","Pastor Paul Adefarasin","https://houseontherock.org.ng","+234 1 000 0000","info@hotr.org.ng","Known for hosting 'The Experience', Africa's largest gospel music concert.","Building a people of destiny.","1994","10000","12","false","true","true","https://houseontherock.org.ng/give"
"Mavuno Church","mavuno-church-nairobi","Non-Denominational","non-denominational","Kenya","Nairobi","Nairobi, Kenya","Pastor Muriithi Wanjau","https://mavunochurch.org","+254 000 0000","info@mavuno.org","A modern, missional church focusing on transforming culture and raising societal leaders.","Turning ordinary people into fearless influencers of society.","2005","5000","10","false","true","true","https://mavunochurch.org/give"
"Village Church","village-church-surrey","Non-Denominational","non-denominational","Canada","Surrey","Surrey, BC, Canada","Pastor Mark Clark","https://thisisvillagechurch.com","+1 604 000 0000","info@village.org","A gospel-centered church in British Columbia with multiple locations and a focus on secular outreach.","Making Jesus known.","2010","5000","8","false","true","true","https://thisisvillagechurch.com/give"
"Jesus Is Lord Church","jesus-is-lord-church-manila","Pentecostal","pentecostal","Philippines","Manila","Manila, Philippines","Bishop Eddie Villanueva","https://jilworldwide.org","+63 2 000 0000","info@jil.org","A major international Pentecostal movement originating in the Philippines with a strong social presence.","Serving the Philippines and the world.","1978","1000000","30","false","true","true","https://jilworldwide.org/give"
"C3 Church Sydney","c3-church-sydney-sydney","Pentecostal","pentecostal","Australia","Sydney","Oxford Falls, Sydney, Australia","Pastor Phil Pringle","https://c3churchglobal.com","+61 2 000 0000","info@c3.org","The founding church of the C3 global movement, focused on creative expression and gospel clarity.","To reach the world for Christ.","1980","5000","10","false","true","true","https://c3churchglobal.com/give"
"Passion City Church","passion-city-church-atlanta","Non-Denominational","non-denominational","USA","Atlanta","Atlanta, GA, USA","Pastor Louie Giglio","https://passioncitychurch.com","+1 404 000 0000","info@passion.org","A church birthed out of the Passion Movement focused on the fame of Jesus.","For the fame of the name of Jesus.","2008","10000","10","false","true","true","https://passioncitychurch.com/give"
"Church of the Highlands","church-of-the-highlands-birmingham","Non-Denominational","non-denominational","USA","Birmingham","Birmingham, AL, USA","Pastor Chris Hodges","https://churchofthehighlands.com","+1 205 000 0000","info@highlands.org","One of the fastest-growing churches in America with numerous campuses across Alabama.","Helping people know God, find freedom, discover purpose, and make a difference.","2001","60000","20","false","true","true","https://churchofthehighlands.com/give"
"Life.Church","life-church-oklahoma-city","Non-Denominational","non-denominational","USA","Oklahoma City","Edmond, OK, USA","Pastor Craig Groeschel","https://life.church","+1 405 000 0000","info@life.church","Pioneers of the YouVersion Bible App and open-access church resources globally.","To lead people to become fully devoted followers of Christ.","1996","80000","25","false","true","true","https://life.church/give"
"Mariners Church","mariners-church-irvine","Non-Denominational","non-denominational","USA","Irvine","Irvine, CA, USA","Pastor Eric Geiger","https://marinerschurch.org","+1 949 000 0000","info@mariners.org","A vibrant community in Orange County with a strong emphasis on root-to-fruit discipleship.","Fearlessly following Jesus.","1963","15000","15","false","true","true","https://marinerschurch.org/give"
"Bayside Church","bayside-church-roseville","Non-Denominational","non-denominational","USA","Roseville","Roseville, CA, USA","Pastor Ray Johnston","https://baysideonline.com","+1 916 000 0000","info@bayside.org","A thriving multi-site church in Northern California known for its community impact.","To build the Kingdom.","1995","20000","18","false","true","true","https://baysideonline.com/give"
"Christ Fellowship","christ-fellowship-palm-beach-gardens","Non-Denominational","non-denominational","USA","Palm Beach Gardens","Palm Beach Gardens, FL, USA","Pastor Todd Mullins","https://christfellowship.church","+1 561 000 0000","info@gochristfellowship.com","A multicultural church in South Florida with a heart for people to know God.","Making it on earth as it is in heaven.","1984","30000","20","false","true","true","https://christfellowship.church/give"
"Willow Creek Community Church","willow-creek-community-church-south-barrington","Non-Denominational","non-denominational","USA","South Barrington","South Barrington, IL, USA","Pastor Dave Dummitt","https://willowcreek.org","+1 224 000 0000","info@willowcreek.org","A pioneer of the seeker-sensitive movement, serving the Chicago area.","To love God, love people, and change the world.","1975","18000","20","false","true","true","https://willowcreek.org/give"
"Grace Community Church","grace-community-church-sun-valley","Non-Denominational","non-denominational","USA","Sun Valley","Sun Valley, CA, USA","Pastor John MacArthur","https://gty.org","+1 818 000 0000","info@gracechurch.org","Known for the expository preaching ministry of John MacArthur and the Masters Seminary.","Teaching the truth and transforming lives.","1956","8000","10","false","true","true","https://gracechurch.org/give"
"Prestonwood Baptist Church","prestonwood-baptist-church-plano","Baptist","baptist","USA","Plano","Plano, TX, USA","Pastor Jack Graham","https://prestonwood.org","+1 972 000 0000","info@prestonwood.org","A leading Southern Baptist church in Texas with a global media ministry.","To glorify God by introducing Jesus Christ as Lord.","1977","45000","25","false","true","true","https://prestonwood.org/give"
"The Rock Church","the-rock-church-san-diego","Non-Denominational","non-denominational","USA","San Diego","San Diego, CA, USA","Pastor Miles McPherson","https://sdrock.com","+1 619 000 0000","info@sdrock.com","Founded by former NFL player Miles McPherson, focusing on youth and urban outreach.","Establish global kingdom impact.","2000","15000","15","false","true","true","https://sdrock.com/give"
"Watermark Community Church","watermark-community-church-dallas","Non-Denominational","non-denominational","USA","Dallas","Dallas, TX, USA","Pastor Blake Holmes","https://watermark.org","+1 214 000 0000","info@watermark.org","A contemporary church in Dallas known for its strong emphasis on community and transparency.","To love God and love others.","1999","12000","12","false","true","true","https://watermark.org/give"
"McLean Bible Church","mclean-bible-church-mclean","Non-Denominational","non-denominational","USA","McLean","McLean, VA, USA","Pastor David Platt","https://mcleanbible.org","+1 703 000 0000","info@mcleanbible.org","An evangelical church in the Washington D.C. area known for radical discipleship and global mission.","To glorify God by making disciples of all nations.","1961","10000","10","false","true","true","https://mcleanbible.org/give"
"Covenant Life Church","covenant-life-church-gaithersburg","Non-Denominational","non-denominational","USA","Gaithersburg","Gaithersburg, MD, USA","Pastor Kevin Rogers","https://covlife.org","+1 301 000 0000","info@covlife.org","A gospel-centered church focused on biblical community and family life.","Knowing God, loving people.","1977","3000","6","false","true","true","https://covlife.org/give"
"Redeemer Presbyterian Church","redeemer-presbyterian-church-new-york","Presbyterian","presbyterian","USA","New York","New York, NY, USA","Pastor Tim Keller","https://redeemer.com","+1 212 000 0000","info@redeemer.com","Founded by Tim Keller, this church has a mission to serve the city of New York through word and deed.","To be a movement for the gospel in the city.","1989","5000","10","false","true","true","https://redeemer.com/give"
"Sovereign Grace Church","sovereign-grace-church-gilbert","Non-Denominational","non-denominational","USA","Gilbert","Gilbert, AZ, USA","Pastor Mark Prater","https://sovereigngrace.com","+1 480 000 0000","info@sovgrace.com","A part of the Sovereign Grace Churches denomination with a focus on reformed theology.","Centering our lives on the Gospel.","1982","1200","5","false","true","true","https://sovereigngrace.com/give"
"Mars Hill Church","mars-hill-church-grand-rapids","Non-Denominational","non-denominational","USA","Grand Rapids","Grand Rapids, MI, USA","Pastor Troy Murphy","https://marshill.org","+1 616 000 0000","info@marshill.org","A community exploring the Way of Jesus in the contemporary world.","Journeying together in faith.","1999","3500","7","false","true","true",null
"Agape International Spiritual Center","agape-international-spiritual-center-los-angeles","Non-Denominational","non-denominational","USA","Los Angeles","Los Angeles, CA, USA","Michael Beckwith","https://agapelive.com","+1 310 000 0000","info@agapelive.com","A trans-denominational community dedicated to truth and global healing.","United in love and truth.","1986","9000","10","false","true","true","https://agapelive.com/give"
"Park Community Church","park-community-church-chicago","Non-Denominational","non-denominational","USA","Chicago","Chicago, IL, USA","Pastor Jackson","https://parkcommunity.church","+1 312 000 0000","info@parkcommunity.org","A multi-site church in Chicago with a heart for urban renewal and discipleship.","To make disciples who make disciples.","1984","4000","8","false","true","true","https://parkcommunity.church/give"
"Cornerstone Chapel","cornerstone-chapel-leesburg","Non-Denominational","non-denominational","USA","Leesburg","Leesburg, VA, USA","Pastor Gary Hamrick","https://cornerstonechapel.net","+1 703 000 0000","info@cornerstonechapel.net","A Calvary Chapel affiliate focused on clear biblical teaching in Northern Virginia.","Equipping the saints for the work of ministry.","1991","6000","7","false","true","true","https://cornerstonechapel.net/give"
"The Village Church","the-village-church-flower-mound","Non-Denominational","non-denominational","USA","Flower Mound","Flower Mound, TX, USA","Pastor Matt Chandler","https://thevillagechurch.net","+1 972 000 0000","info@thevillagechurch.net","A gospel-centered church in the Dallas area focused on group-based discipleship.","To bring glory to God by making disciples.","2002","5000","9","false","true","true","https://thevillagechurch.net/give"
"Hillsong Phoenix","hillsong-phoenix-phoenix","Pentecostal","pentecostal","USA","Phoenix","Phoenix, AZ, USA","Pastor Terry","https://hillsong.com/phoenix","+1 602 000 0000","phoenix@hillsong.com","A branch of Hillsong serving the Southwest with modern worship and teaching.","Welcome Home to Phoenix.","2016","3000","6","false","true","true","https://hillsong.com/give"
"Christ the King Church","christ-the-king-church-houston","Catholic","catholic","USA","Houston","Houston, TX, USA","Fr. John","https://ctkhouston.org","+1 713 000 0000","info@ctkhouston.org","A large Catholic parish in the Houston area with a strong focus on liturgy and community.","Living the faith together.","1950","5000","8","false","true","true",null
"St. Patrick's Cathedral","st.-patricks-cathedral-new-york","Catholic","catholic","USA","New York","5th Ave, New York, NY, USA","Cardinal Timothy Dolan","https://saintpatrickscathedral.org","+1 212 753 2261","info@stpatricks.org","The seat of the Roman Catholic Archdiocese of New York, a neo-gothic landmark on 5th Avenue.","A center of prayer in the heart of the city.","1879","10000","15","false","true","true",null
"Grace Cathedral","grace-cathedral-san-francisco","Anglican","anglican","USA","San Francisco","1100 California St, San Francisco, CA, USA","Dean Malcolm Young","https://gracecathedral.org","+1 415 749 6300","info@gracecathedral.org","The Episcopal cathedral on Nob Hill, known for its labyrinth and interfaith efforts.","A house of prayer for all people.","1849","2000","10","false","true","true","https://gracecathedral.org/give"
"Washington National Cathedral","washington-national-cathedral-washington-dc","Anglican","anglican","USA","Washington D.C.","3101 Wisconsin Ave NW, Washington, D.C., USA","Dean Randy Hollerith","https://cathedral.org","+1 202 537 6200","info@cathedral.org","The spiritual home for the nation, a venue for major religious and civic ceremonies.","To be a catalyst for spiritual harmony.","1907","5000","20","false","true","true","https://cathedral.org/give"
"Old North Church","old-north-church-boston","Anglican","anglican","USA","Boston","193 Salem St, Boston, MA, USA","Rev. Nikki","https://oldnorth.com","+1 617 523 6676","info@oldnorth.com","The oldest standing church building in Boston, famous for Paul Revere's lantern signal.","Legacy of liberty and faith.","1723","200","5","false","true","true",null
"Trinity Church Wall Street","trinity-church-wall-street-new-york","Anglican","anglican","USA","New York","75 Broadway, New York, NY, USA","Rev. Phil Jackson","https://trinitywallstreet.org","+1 212 602 0800","info@trinitywallstreet.org","An iconic Episcopal parish located at the intersection of Wall Street and Broadway.","Building a better neighborhood for all.","1697","2000","12","false","true","true","https://trinitywallstreet.org/give"
"Abyssinian Baptist Church","abyssinian-baptist-church-new-york","Baptist","baptist","USA","New York","132 W 138th St, New York, NY, USA","Rev. Kevin Johnson","https://abyssinian.org","+1 212 368 4471","info@abyssinian.org","A historic African American Baptist church in Harlem, central to the civil rights movement.","Faith in Harlem.","1808","5000","10","false","true","true",null
"Ebenezer Baptist Church","ebenezer-baptist-church-atlanta","Baptist","baptist","USA","Atlanta","407 Auburn Ave NE, Atlanta, GA, USA","Rev. Raphael Warnock","https://ebenezeratl.org","+1 404 688 7300","info@ebenezeratl.org","The spiritual home of Dr. Martin Luther King Jr., focusing on social justice and spiritual growth.","Continuing the dream.","1886","6000","12","false","true","true",null
"The Riverside Church","the-riverside-church-new-york","Non-Denominational","non-denominational","USA","New York","490 Riverside Dr, New York, NY, USA","Rev. Adriene Thorne","https://trcnyc.org","+1 212 870 6700","info@trcnyc.org","A multi-denominational, interracial, and international church on the Upper West Side of Manhattan.","To be a beacon of progressive faith.","1930","3000","15","false","true","true","https://trcnyc.org/give"
"Crystal Cathedral","crystal-cathedral-garden-grove","Reformed","reformed","USA","Garden Grove","Garden Grove, CA, USA","Fr. Christopher Smith","https://christcathedralcalifornia.org","+1 714 971 2141","info@christcathedral.org","Now known as Christ Cathedral (Catholic), this iconic glass building was formerly home to the Hour of Power.","Icon of grace.","1955","10000","12","false","true","true",null
"Moody Church","moody-church-chicago","Non-Denominational","non-denominational","USA","Chicago","1635 N LaSalle Dr, Chicago, IL, USA","Pastor Philip Miller","https://moodychurch.org","+1 312 327 8600","info@moodychurch.org","A historic evangelical church in Chicago founded by D.L. Moody.","To know Christ and make Him known.","1864","4000","10","false","true","true","https://moodychurch.org/give"
"Second Presbyterian Church","second-presbyterian-church-indianapolis","Presbyterian","presbyterian","USA","Indianapolis","Indianapolis, IN, USA","Rev. Chris Henry","https://secondchurch.org","+1 317 253 6461","info@secondchurch.org","A leading Presbyterian congregation in the Midwest focused on mission and community.","Following Jesus into the city.","1838","3000","8","false","true","true",null
"First Presbyterian Church of Houston","first-presbyterian-church-of-houston-houston","Presbyterian","presbyterian","USA","Houston","5300 Main St, Houston, TX, USA","Rev. Jim Birchfield","https://fpchouston.org","+1 713 620 6500","info@fpchouston.org","A historic congregation in the museum district of Houston focused on transformation.","In the city, for the city.","1839","2500","10","false","true","true","https://fpchouston.org/give"
"Coral Ridge Presbyterian Church","coral-ridge-presbyterian-church-fort-lauderdale","Presbyterian","presbyterian","USA","Fort Lauderdale","Fort Lauderdale, FL, USA","Rev. Rob Pacienza","https://crpc.org","+1 954 771 8840","info@crpc.org","An evangelical Presbyterian church known for its media ministry and cultural engagement.","To equip the church to reach the world.","1960","2000","8","false","true","true","https://crpc.org/give"
"Tenth Presbyterian Church","tenth-presbyterian-church-philadelphia","Presbyterian","presbyterian","USA","Philadelphia","1701 Delancey St, Philadelphia, PA, USA","Rev. Liam Goligher","https://tenth.org","+1 215 735 7688","info@tenth.org","A historic Reformed Presbyterian church in center-city Philadelphia.","Holding forth the Word of life.","1829","1500","7","false","true","true",null
"Park Street Church","park-street-church-boston","Non-Denominational","non-denominational","USA","Boston","1 Park St, Boston, MA, USA","Rev. Mark Booker","https://parkstreet.org","+1 617 523 3383","info@parkstreet.org","A historic evangelical church located on the Freedom Trail in Boston.","In the heart of the city, for the heart of the city.","1809","1000","8","false","true","true","https://parkstreet.org/give"
"National City Christian Church","national-city-christian-church-washington-dc","Non-Denominational","non-denominational","USA","Washington D.C.","5 Thomas Cir NW, Washington, D.C., USA","Rev. Amy","https://nationalcitycc.org","+1 202 232 0323","info@nationalcitycc.org","The national cathedral for the Christian Church (Disciples of Christ) in the capital.","Diverse people, one Spirit.","1843","500","5","false","true","true",null
"Glide Memorial Church","glide-memorial-church-san-francisco","Methodist","methodist","USA","San Francisco","330 Ellis St, San Francisco, CA, USA","Rev. Marvin White","https://glide.org","+1 415 674 6000","info@glide.org","A radically inclusive congregation in San Francisco known for its extensive social services.","To create a radically inclusive community.","1929","5000","20","false","true","true","https://glide.org/give"
"Foundry United Methodist Church","foundry-united-methodist-church-washington-dc","Methodist","methodist","USA","Washington D.C.","1500 16th St NW, Washington, D.C., USA","Rev. Ginger Gaines-Cirelli","https://foundryumc.org","+1 202 332 4010","info@foundryumc.org","A historic Methodist church in the capital known for social activism and inclusion.","All are welcome.","1814","1500","8","false","true","true",null
"St. James Cathedral","st.-james-cathedral-seattle","Catholic","catholic","USA","Seattle","804 9th Ave, Seattle, WA, USA","Fr. Michael Ryan","https://stjames-cathedral.org","+1 206 622 3559","info@stjames-cathedral.org","The seat of the Catholic Archdiocese of Seattle, known for its outreach to the homeless.","A house of prayer and service.","1907","4000","10","false","true","true",null
"Cathedral of Our Lady of the Angels","cathedral-of-our-lady-of-the-angels-los-angeles","Catholic","catholic","USA","Los Angeles","555 W Temple St, Los Angeles, CA, USA","Archbishop Jose Gomez","https://olacathedral.org","+1 213 680 5200","info@olacathedral.org","A postmodern cathedral serving as the seat of the Archdiocese of Los Angeles.","Spiritual home for the City of Angels.","2002","12000","15","false","true","true",null
"St. Paul's Chapel","st.-pauls-chapel-new-york","Anglican","anglican","USA","New York","209 Broadway, New York, NY, USA","Rev. Phil","https://trinitywallstreet.org/st-pauls-chapel","+1 212 602 0800","info@stpauls.org","Part of Trinity Wall Street, it is the oldest surviving church building in Manhattan.","History and hope.","1766","500","5","false","true","true",null
"Bruton Parish Church","bruton-parish-church-williamsburg","Anglican","anglican","USA","Williamsburg","Williamsburg, VA, USA","Rev. Chris","https://brutonparish.org","+1 757 229 2891","info@brutonparish.org","A historic Episcopal church located in Colonial Williamsburg, active since the 17th century.","Preserving the legacy.","1674","1000","6","false","true","true",null
"Christ Church Alexandria","christ-church-alexandria-alexandria","Anglican","anglican","USA","Alexandria","118 N Washington St, Alexandria, VA, USA","Rev. Noelle","https://historicchristchurch.org","+1 703 549 1450","info@ccalex.org","A historic Episcopal church where George Washington was a vestryman.","Rooted in history, growing in grace.","1773","1200","7","false","true","true",null
"St. John's Church Lafayette Square","st.-johns-church-lafayette-square-washington-dc","Anglican","anglican","USA","Washington D.C.","1525 H St NW, Washington, D.C., USA","Rev. Rob","https://stjohns-dc.org","+1 202 347 8766","info@stjohns-dc.org","Known as the 'Church of the Presidents', located directly across from the White House.","Faith in the public square.","1815","800","5","false","true","true",null
"Zion Baptist Church","zion-baptist-church-philadelphia","Baptist","baptist","USA","Philadelphia","Philadelphia, PA, USA","Rev. Leon Sullivan","https://zionbaptistphila.org","+1 215 223 5460","info@zionbaptist.org","A historic African American church in Philadelphia known for its economic and social programs.","Progress through faith.","1882","2000","8","false","true","true",null
"First Baptist Church Dallas","first-baptist-church-dallas-dallas","Baptist","baptist","USA","Plano","Dallas, TX, USA","Pastor Robert Jeffress","https://firstdallas.org","+1 214 969 0111","info@firstdallas.org","A prominent Southern Baptist church in Dallas with a long history of influence in Texas.","Transforming the world for Christ.","1868","15000","15","false","true","true","https://firstdallas.org/give"
"Bellevue Baptist Church","bellevue-baptist-church-memphis","Baptist","baptist","USA","Memphis","2000 Appling Rd, Cordova, TN, USA","Pastor Steve Gaines","https://bellevue.org","+1 901 347 2000","info@bellevue.org","One of the largest churches in the Southern Baptist Convention, based in Memphis.","To love God, love people, and share Jesus.","1903","30000","20","false","true","true","https://bellevue.org/give"
"Highland Park Baptist Church","highland-park-baptist-church-chattanooga","Baptist","baptist","USA","Chattanooga","Chattanooga, TN, USA","Pastor Jeremy","https://hpbc.org","+1 423 698 8601","info@hpbc.org","A historic Baptist church in Tennessee with a long legacy of missionary support.","Faith for all generations.","1890","2000","6","false","true","true",null
"The Moody Church","the-moody-church-chicago","Non-Denominational","non-denominational","USA","Chicago","Chicago, IL, USA","Pastor Philip Miller","https://moodychurch.org","+1 312 327 8600","info@moodychurch.org","A landmark of evangelical faith in Chicago, founded by D.L. Moody.","To the glory of God.","1864","4000","10","false","true","true","https://moodychurch.org/give"
"Knox Presbyterian Church","knox-presbyterian-church-toronto","Presbyterian","presbyterian","Canada","Toronto","630 Spadina Ave, Toronto, ON, Canada","Rev. Phil","https://knoxtoronto.org","+1 416 921 8993","info@knoxtoronto.org","A historic and evangelical Presbyterian congregation in downtown Toronto.","A light for the city.","1820","800","6","false","true","true",null
"Metropolitan United Church","metropolitan-united-church-toronto","Methodist","methodist","Canada","Toronto","56 Queen St E, Toronto, ON, Canada","Rev. Jason","https://metunited.ca","+1 416 363 0331","info@metunited.ca","A progressive United Church of Canada in the heart of Toronto, known for its carillon.","The downtown cathedral.","1818","1000","8","false","true","true",null
"St. James Cathedral Toronto","st.-james-cathedral-toronto-toronto","Anglican","anglican","Canada","Toronto","65 Church St, Toronto, ON, Canada","Dean Stephen","https://stjamescathedral.ca","+1 416 364 7865","info@stjamescathedral.ca","The seat of the Anglican Diocese of Toronto, a masterpiece of Gothic Revival architecture.","Center for the city.","1797","1500","10","false","true","true",null
"Christ Church Cathedral Montreal","christ-church-cathedral-montreal-montreal","Anglican","anglican","Canada","Montreal","635 Saint-Catherine St W, Montreal, QC, Canada","Dean Bertrand","https://montrealcathedral.ca","+1 514 843 6577","info@montrealcathedral.ca","A beautiful neo-gothic cathedral in downtown Montreal, known for its music and social programs.","Faith in Montreal.","1814","1000","7","false","true","true",null
"Notre-Dame Basilica","notre-dame-basilica-montreal","Catholic","catholic","Canada","Montreal","110 Notre-Dame St W, Montreal, QC, Canada","Fr. Manseau","https://basiliquenotredame.ca","+1 514 842 2925","info@basiliquend.ca","A masterpiece of Gothic Revival architecture and a spiritual heart for the French-Canadian community.","Splendor for the glory of God.","1829","5000","12","false","true","true",null
"St. Joseph's Oratory","st.-josephs-oratory-montreal","Catholic","catholic","Canada","Montreal","3800 Queen Mary Rd, Montreal, QC, Canada","Fr. Rector","https://saint-joseph.org","+1 514 733 8211","info@saint-joseph.org","A major international pilgrimage site and Canada's largest church, founded by Saint André Bessette.","Hope and healing in the Oratory.","1904","10000","20","false","true","true",null
"St. Michael's Cathedral Basilica","st.-michaels-cathedral-basilica-toronto","Catholic","catholic","Canada","Toronto","65 Bond St, Toronto, ON, Canada","Cardinal Collins","https://stmichaelscathedral.com","+1 416 364 0234","info@stmichaelscathedral.com","The mother church of the Roman Catholic Archdiocese of Toronto, recently restored to its full splendor.","Spiritual home for the Archdiocese.","1845","4000","12","false","true","true",null
"Coastal Church","coastal-church-vancouver","Non-Denominational","non-denominational","Canada","Vancouver","1160 W Georgia St, Vancouver, BC, Canada","Pastor David Koop","https://coastalchurch.org","+1 604 684 8474","info@coastalchurch.org","A modern church in the heart of downtown Vancouver with a focus on city transformation.","Helping make the city a better place.","1994","2000","8","false","true","true","https://coastalchurch.org/give"
"Tenth Church","tenth-church-vancouver","Non-Denominational","non-denominational","Canada","Vancouver","11 W 10th Ave, Vancouver, BC, Canada","Pastor Ken Shigematsu","https://tenth.ca","+1 604 876 2181","info@tenth.ca","A large, multicultural community in Vancouver known for its deep spirituality and justice work.","To help people know and follow Jesus.","1897","4000","10","false","true","true","https://tenth.ca/give"
"The Peoples Church","the-peoples-church-toronto","Non-Denominational","non-denominational","Canada","Toronto","374 Sheppard Ave E, Toronto, ON, Canada","Pastor Brett","https://thepeopleschurch.ca","+1 416 222 3341","info@thepeopleschurch.ca","A globally focused evangelical church in Toronto known for its missions and multiculturalism.","To reach people with the Gospel.","1928","4000","12","false","true","true","https://thepeopleschurch.ca/give"
"Central Heights Church","central-heights-church-abbotsford","Non-Denominational","non-denominational","Canada","Abbotsford","Abbotsford, BC, Canada","Pastor Kevin","https://centralheights.ca","+1 604 853 0724","info@centralheights.ca","A community-oriented church in the Fraser Valley focused on spiritual growth.","Rooted in Christ.","1950","1500","6","false","true","true",null
"Southside Community Church","southside-community-church-surrey","Non-Denominational","non-denominational","Canada","Surrey","Surrey, BC, Canada","Pastor South","https://southside.ca","+1 604 000 0000","info@southside.org","A welcoming community in Surrey part of the Free Methodist tradition.","Real people, real faith.","1990","1000","5","false","true","true",null
"Beulah Alliance Church","beulah-alliance-church-edmonton","Non-Denominational","non-denominational","Canada","Edmonton","Edmonton, AB, Canada","Pastor Keith","https://beulah.ca","+1 780 486 4010","info@beulah.ca","A large alliance church in Edmonton focused on global mission and local discipleship.","Disciples making disciples.","1921","3000","10","false","true","true","https://beulah.ca/give"
"Centre Street Church","centre-street-church-calgary","Non-Denominational","non-denominational","Canada","Calgary","Calgary, AB, Canada","Pastor Jerry Luck","https://cschurch.ca","+1 403 293 3900","info@cschurch.ca","One of Canada's largest evangelical churches, serving the Calgary area.","Leading people to Jesus.","1958","6000","15","false","true","true","https://cschurch.ca/give"
"Calvary Temple Winnipeg","calvary-tempie-winnipeg-winnipeg","Pentecostal","pentecostal","Canada","Winnipeg","Winnipeg, MB, Canada","Pastor Bruce","https://ctwinnipeg.com","+1 204 943 4551","info@ctwinnipeg.com","A landmark Pentecostal church in Winnipeg with a heart for urban missions.","Faith in Winnipeg.","1907","2000","8","false","true","true",null
"Saint Mary's University Church","saint-marys-university-church-halifax","Catholic","catholic","Canada","Halifax","Halifax, NS, Canada","Fr. John","https://saintmaryscathedral.ca","+1 902 423 3057","info@halifax.org","The historic cathedral church serving the Halifax community and the local university.","Sanctuary for the east.","1820","1000","5","false","true","true",null
"Metropolitan Bible Church","metropolitan-bible-church-ottawa","Non-Denominational","non-denominational","Canada","Ottawa","Ottawa, ON, Canada","Pastor Randy","https://metbiblechurch.ca","+1 613 238 8182","info@metbiblechurch.ca","A central evangelical church in the capital city of Ottawa.","Biblical truth in the capital.","1912","2500","10","false","true","true","https://metbiblechurch.ca/give"
"The Rock Church Halifax","the-rock-church-halifax-halifax","Non-Denominational","non-denominational","Canada","Halifax","Halifax, NS, Canada","Pastor Rock","https://therockchurch.ca","+1 902 000 0000","info@therock.org","A modern, evangelistic church serving the Halifax metropolitan area.","Rock of hope.","2000","1000","5","false","true","true",null
"City Church Montreal","city-church-montreal-montreal","Non-Denominational","non-denominational","Canada","Montreal","Montreal, QC, Canada","Pastor Chris","https://citychurch.ca","+1 514 000 0000","info@citychurch.org","A contemporary, multi-cultural church in the heart of Montreal.","Montreal for Christ.","2005","800","4","false","true","true",null
"Grace Toronto Church","grace-toronto-church-toronto","Presbyterian","presbyterian","Canada","Toronto","Toronto, ON, Canada","Pastor Dan MacDonald","https://gracetoronto.ca","+1 416 000 0000","info@gracetoronto.ca","A PCA church plant in downtown Toronto focused on city transformation.","Gospel for Toronto.","2008","600","4","false","true","true","https://gracetoronto.ca/give"
"St. Paul's Bloor Street","st.-pauls-bloor-street-toronto","Anglican","anglican","Canada","Toronto","227 Bloor St E, Toronto, ON, Canada","Rev. Canon Jenny","https://stpaulsbloor.org","+1 416 961 8116","info@stpaulsbloor.org","A vibrant Anglican church in the heart of Toronto focused on worship and outreach.","Witnessing to Christ on Bloor.","1842","1200","8","false","true","true",null
"Deeper Life Bible Church","deeper-life-bible-church-lagos","Pentecostal","pentecostal","Nigeria","Lagos","Gbagada, Lagos, Nigeria","Pastor William Kumuyi","https://dclm.org","+234 1 000 0000","info@dclm.org","A holiness-focused Pentecostal movement with one of the largest congregational networks in Nigeria.","Restoring the apostolic faith.","1982","1000000","50","false","true","true","https://dclm.org/give"
"Mountain of Fire and Miracles","mountain-of-fire-and-miracles-lagos","Pentecostal","pentecostal","Nigeria","Lagos","Yaba, Lagos, Nigeria","Dr. Daniel Kolawole Olukoya","https://mountainoffire.org","+234 1 000 0000","info@mfm.org.ng","Known for its focus on spiritual warfare and its massive 'Prayer City' on the Lagos-Ibadan expressway.","Prayer that works.","1989","500000","40","false","true","true","https://mountainoffire.org/give"
"The Apostolic Church Nigeria","the-apostolic-church-nigeria-lagos","Apostolic","charismatic","Nigeria","Lagos","Lagos, Nigeria","Pastor Emmanuel Awojide","https://tacn.org.ng","+234 1 000 0000","info@tacn.org.ng","One of the oldest Pentecostal denominations in Nigeria with a rich apostolic heritage.","Maintaining the apostolic order.","1918","1000000","35","false","true","true",null
"Celestial Church of Christ","celestial-church-of-christ-lagos","Apostolic","charismatic","Nigeria","Lagos","Makoko, Lagos, Nigeria","Pastor Mobiyina Oshoffa","http://celestialchurch.com","+234 1 000 0000","info@ccc.org.ng","An indigenous African Instituted Church known for its unique liturgy and white garments.","Worship in the Spirit.","1947","500000","30","false","true","true",null
"Cherubim and Seraphim","cherubim-and-seraphim-lagos","Apostolic","charismatic","Nigeria","Lagos","Lagos, Nigeria","Apostle Moses Orimolade","http://csmc.org","+234 1 000 0000","info@csmc.org","One of the first indigenous churches in Nigeria, blending Christian and African spiritual traditions.","Seeking the face of God.","1925","400000","25","false","true","true",null
"Methodist Church Nigeria","methodist-church-nigeria-lagos","Methodist","methodist","Nigeria","Lagos","Marina, Lagos, Nigeria","Prelate Samuel Uche","http://methodistnigeria.org","+234 1 000 0000","info@methodist.org.ng","The oldest Methodist body in Nigeria, originating from British missionary efforts.","Serving Christ and Nigeria.","1842","2000000","40","false","true","true",null
"Nigerian Baptist Convention","nigerian-baptist-convention-lagos","Baptist","baptist","Nigeria","Lagos","Lagos, Nigeria","Rev. Israel Akanji","http://baptistnigeria.org","+234 1 000 0000","info@baptist.org.ng","The umbrella body for Baptist churches in Nigeria, focusing on missions and education.","Proclaiming the kingdom.","1850","5000000","100","false","true","true",null
"Salvation Ministries","salvation-ministries-port-harcourt","Pentecostal","pentecostal","Nigeria","Port Harcourt","Port Harcourt, Rivers, Nigeria","Pastor David Ibiyeomie","https://smhos.org","+234 84 000 0000","info@smhos.org","A rapidly growing Pentecostal church in the Niger Delta region focused on prosperity and holiness.","Re-establishing the kingdom of God.","1997","50000","20","false","true","true","https://smhos.org/give"
"Covenant Christian Centre","covenant-christian-centre-lagos","Charismatic","charismatic","Nigeria","Lagos","Iganmu, Lagos, Nigeria","Pastor Poju Oyemade","https://insightsforliving.org","+234 1 000 0000","info@insights.org.ng","A contemporary church in Lagos focused on the application of faith in professional life and nation building.","Equipping believers for society.","1994","15000","10","false","true","true","https://insightsforliving.org/give"
"Celebration Church International","celebration-church-international-lagos","Pentecostal","pentecostal","Nigeria","Lagos","Lagos, Nigeria","Pastor Emmanuel Iren","https://celebrationchurchint.org","+234 1 000 0000","info@celebration.org.ng","A vibrant, youth-led ministry focused on progress and joy in the faith.","Endless progress and joy.","2012","10000","8","false","true","true","https://celebrationchurchint.org/give"
"Daystar Christian Centre","daystar-christian-centre-lagos","Non-Denominational","non-denominational","Nigeria","Lagos","Oregun, Ikeja, Lagos, Nigeria","Pastor Sam Adeyemi","https://daystarng.org","+234 1 000 0000","info@daystarng.org","A center for leadership and transformation, focusing on practical life skills and spiritual growth.","Raising role models.","1995","20000","15","false","true","true","https://daystarng.org/give"
"The Elevation Church","the-elevation-church-lagos","Non-Denominational","non-denominational","Nigeria","Lagos","Lekki, Lagos, Nigeria","Pastor Godman Akinlabi","https://elevationng.org","+234 1 000 0000","info@elevationng.org","A modern church focused on making people greatness-ready and serving the urban community.","To make greatness common.","2010","10000","10","false","true","true","https://elevationng.org/give"
"Kingsway International Christian Centre","kingsway-international-christian-centre-lagos","Charismatic","charismatic","Nigeria","Lagos","Maryland, Lagos, Nigeria","Pastor Matthew Ashimolowo","https://kicc.org.ng","+234 1 000 0000","info@kicc.org.ng","The Nigerian branch of the London-based megachurch focusing on wealth and success.","Raising champions.","1992","5000","8","false","true","true","https://kicc.org.ng/give"
"Full Life Christian Centre","full-life-christian-centre-uyo","Pentecostal","pentecostal","Nigeria","Uyo","Uyo, Akwa Ibom, Nigeria","Rev. Ntia I. Ntia","https://fulllifefoundation.com","+234 85 000 0000","info@fulllife.org.ng","A major spiritual lighthouse in Akwa Ibom focused on the fullness of God's power.","Life to the full.","2000","20000","12","false","true","true",null
"Royal House of Grace","royal-house-of-grace-port-harcourt","Pentecostal","pentecostal","Nigeria","Port Harcourt","Port Harcourt, Nigeria","Apostle Zilly Aggrey","https://royalhouseofgrace.org","+234 84 000 0000","info@royalhouse.org.ng","A prophetic and apostolic ministry focused on grace and dominion in the Niger Delta.","Royalty by grace.","1992","15000","10","false","true","true",null
"Word of Life Bible Church","word-of-life-bible-church-warri","Pentecostal","pentecostal","Nigeria","Warri","Warri, Delta State, Nigeria","Pastor Ayo Oritsejafor","https://wolbc.org","+234 53 000 0000","info@wolbc.org","The spiritual home of the former CAN president, known for its focus on the Word and empowerment.","Winning the world for Christ.","1987","20000","15","false","true","true",null
"Assemblies of God Nigeria","assemblies-of-god-nigeria-enugu","Pentecostal","pentecostal","Nigeria","Enugu","Enugu, Nigeria","Rev. Chidi Okoroafor","http://agnigeria.org","+234 42 000 0000","info@agnigeria.org.zw","A classic Pentecostal denomination with a strong presence across eastern Nigeria.","Proclaiming the Pentecostal power.","1934","2000000","50","false","true","true",null
"ECWA (Evangelical Church Winning All)","ecwa-evangelical-church-winning-all-jos","Evangelical","evangelical","Nigeria","Jos","Jos, Plateau State, Nigeria","Rev. Job Mallam","https://ecwang.org","+234 73 000 0000","info@ecwang.org","One of the largest evangelical denominations in Northern Nigeria, founded by SIM.","Preaching the Word to the unreached.","1954","5000000","100","false","true","true",null
"The Salvation Army Nigeria","the-salvation-army-nigeria-lagos","Salvation Army","non-denominational","Nigeria","Lagos","Lagos, Nigeria","Colonel Victor Leslie","http://salvationarmy.org.ng","+234 1 000 0000","info@salvationarmy.org.ng","An international movement known for its humanitarian and social services in Nigeria.","Heart to God, hand to man.","1920","200000","30","false","true","true",null
"Omega Fire Ministries","omega-fire-ministries-auchi","Pentecostal","pentecostal","Nigeria","Auchi","Auchi, Edo State, Nigeria","Apostle Johnson Suleman","https://omegafireministries.org","+234 57 000 0000","info@ofm.org.ng","A vibrant charismatic ministry in the south-south focused on healing and the prophetic.","Restoring the fire of God.","2004","30000","12","false","true","true","https://omegafireministries.org/give"
"All Saints' Cathedral Nairobi","all-saints-cathedral-nairobi-nairobi","Anglican","anglican","Kenya","Nairobi","Kenyatta Ave, Nairobi, Kenya","Provost Sammy Wainaina","https://allsaintsbundle.co.ke","+254 20 272 1077","info@allsaintscathedral.org","A national landmark and the seat of the Anglican Archbishop of Kenya, known for its historic role in governance.","To reach the world for Christ through word and service.","1917","10000","15","false","true","true","https://allsaintsbundle.co.ke/give"
"Nairobi Baptist Church","nairobi-baptist-church-nairobi","Baptist","baptist","Kenya","Nairobi","Ngong Rd, Nairobi, Kenya","Pastor Munengi Mulandi","https://nairobibaptist.co.ke","+254 20 272 3230","info@nairobibaptist.org","An evangelical community with a rich history of Bible teaching and student ministry in Nairobi.","Know Christ and make Him known.","1958","5000","10","false","true","true","https://nairobibaptist.co.ke/give"
"Parklands Baptist Church","parklands-baptist-church-nairobi","Baptist","baptist","Kenya","Nairobi","Waiyaki Way, Nairobi, Kenya","Pastor Ambrose Nyangao","https://parklandsbaptist.org","+254 20 000 0000","info@parklandsbaptist.org","A multicultural church focused on family life and community impact.","Impacting lives.","1976","6000","12","false","true","true","https://parklandsbaptist.org/give"
"Chrisco Central Church","chrisco-central-church-nairobi","Pentecostal","pentecostal","Kenya","Nairobi","Nairobi, Kenya","Pastor Dass","https://chrisco-church.org","+254 20 000 0000","info@chrisco.org","A long-standing Pentecostal presence in Nairobi with a focus on holistic ministry.","Christ is the Answer.","1978","3000","6","false","true","true",null
"Jesus Celebration Centre","jesus-celebration-centre-mombasa","Pentecostal","pentecostal","Kenya","Mombasa","Bamburi, Mombasa, Kenya","Bishop Wilfred Lai","https://jccmombasa.org","+254 41 000 0000","info@jcc.org","One of the largest churches in the coastal region of Kenya, focused on revival and teaching.","Celebrating Jesus in Mombasa.","1988","15000","10","false","true","true","https://jccmombasa.org/give"
"Deliverance Church Umoja","deliverance-church-umoja-nairobi","Pentecostal","pentecostal","Kenya","Nairobi","Umoja, Nairobi, Kenya","Bishop J.B. Masinde","https://dcumoja.org","+254 20 000 0000","info@dcumoja.org","A foundational Pentecostal community in the Eastlands area of Nairobi.","Raising a people for God's glory.","1984","5000","8","false","true","true","https://dcumoja.org/give"
"Faith Evangelistic Ministry","faith-evangelistic-ministry-nairobi","Charismatic","charismatic","Kenya","Nairobi","Karen, Nairobi, Kenya","Rev. Teresia Wairimu","https://fem-international.org","+254 20 000 0000","info@fem.org","Known for its large-scale evangelistic crusades and powerful teaching ministry in Nairobi.","Winning the lost.","1989","8000","6","false","true","true","https://fem-international.org/give"
"Holy Family Basilica","holy-family-basilica-nairobi","Catholic","catholic","Kenya","Nairobi","City Square, Nairobi, Kenya","Cardinal John Njue","https://holyfamilybasilica.com","+254 20 222 6660","info@holyfamily.org","The central Catholic cathedral in Nairobi, serving as a beacon of faith for the metropolitan area.","A family for all.","1904","10000","15","false","true","true",null
"CITAM (Christ Is The Answer Ministries)","citam-christ-is-the-answer-ministries-nairobi","Pentecostal","pentecostal","Kenya","Nairobi","Valley Rd, Nairobi, Kenya","Bishop Calisto Odede","https://citam.org","+254 20 272 3700","info@citam.org","An evangelical, English-speaking church network known for its media ministry and urban focus.","To know God and make Him known.","1959","50000","20","false","true","true","https://citam.org/give"
"Winner's Chapel Nairobi","winners-chapel-nairobi-nairobi","Pentecostal","pentecostal","Kenya","Nairobi","Mbagathi Way, Nairobi, Kenya","Pastor David","https://winnerschapelnairobi.org","+254 20 000 0000","info@winners.org","The Kenyan headquarters of the Living Faith Church Worldwide, known for its focus on faith and prosperity.","Dominion through faith.","1995","10000","10","false","true","true","https://winnerschapelnairobi.org/give"
"AIC Milimani","aic-milimani-nairobi","Evangelical","evangelical","Kenya","Nairobi","Milimani, Nairobi, Kenya","Pastor John","https://aicmilimani.org","+254 20 271 2300","info@aicmilimani.org","The flagship church of the Africa Inland Church in Nairobi, with a focus on traditional evangelical values.","Serving in the heart of the city.","1970","4000","8","false","true","true",null
"Mamlaka Hill Chapel","mamlaka-hill-chapel-nairobi","Evangelical","evangelical","Kenya","Nairobi","Mamlaka Rd, Nairobi, Kenya","Pastor Charles","https://mamlakahillchapel.org","+254 20 272 8214","info@mamlaka.org","A vibrant church near the University of Nairobi focused on student ministry and city transformation.","To reach the city.","1990","3000","6","false","true","true","https://mamlakahillchapel.org/give"
"Karura Community Chapel","karura-community-chapel-nairobi","Non-Denominational","non-denominational","Kenya","Nairobi","Limuru Rd, Nairobi, Kenya","Pastor Steve","https://karurachapel.org","+254 20 000 0000","info@karura.org","A contemporary community church located near the Karura forest.","Serving the northern suburbs.","1998","2500","5","false","true","true",null
"Presbyterian Church of East Africa (St. Andrews)","presbyterian-church-of-east-africa-st-andrews-nairobi","Presbyterian","presbyterian","Kenya","Nairobi","State House Rd, Nairobi, Kenya","Rev. Dr. Robert","https://pceastandrews.org","+254 20 272 1650","info@standrews.org","A historic Presbyterian congregation in Nairobi with deep roots in education and mission work.","Preserving the heritage.","1910","4000","10","false","true","true",null
"Seventh-Day Adventist Church Maxwell","seventh-day-adventist-church-maxwell-nairobi","Seventh-day Adventist","non-denominational","Kenya","Nairobi","Maxwell, Nairobi, Kenya","Pastor Max","https://maxwell.adventist.org","+254 20 000 0000","info@maxwell.org","A leading SDA congregation in Nairobi focused on health and prophecy.","Preparing for the Second Coming.","1960","3000","7","false","true","true",null
"Our Lady of Consolata Church","our-lady-of-consolata-church-nairobi","Catholic","catholic","Kenya","Nairobi","Westlands, Nairobi, Kenya","Fr. Rector","https://consolata.org","+254 20 000 0000","info@consolata.org","A vibrant Catholic parish in the Westlands area known for its Consolata missionary heritage.","Consolations of the Spirit.","1965","5000","8","false","true","true",null
"St. Peter Claver's Catholic Church","st.-peter-clavers-catholic-church-nairobi","Catholic","catholic","Kenya","Nairobi","Racecourse Rd, Nairobi, Kenya","Fr. Peter","https://stpeterclaver.org","+254 20 000 0000","info@stpeter.org","A historic parish in the downtown area serving a large urban population.","Faith in the city center.","1922","6000","9","false","true","true",null
"Lavington United Church","lavington-united-church-nairobi","Non-Denominational","non-denominational","Kenya","Nairobi","Lavington, Nairobi, Kenya","Rev. Lavington","https://lavingtonunited.org","+254 20 000 0000","info@lavington.org","An inter-denominational church serving the Lavington residential community.","United in love.","1960","2000","5","false","true","true",null
"St. Paul's University Chapel","st.-pauls-university-chapel-nairobi","Non-Denominational","non-denominational","Kenya","Nairobi","Nairobi, Kenya","Rev. Dr. Paul","https://spu.ac.ke","+254 000 0000","info@spu.org","Serving the academic community of St. Paul's University and the public.","Faith and learning.","1955","1500","4","false","true","true",null
"Gethsemane Garden of Blessing","gethsemane-garden-of-blessing-mombasa","Pentecostal","pentecostal","Kenya","Mombasa","Mombasa, Kenya","Pastor Geth","https://gethsemane.org","+254 000 0000","info@gethsemane.org","A major Pentecostal center on the coast focused on prayer and community.","Blessings in the garden.","1990","4000","6","false","true","true",null`;

function parseCSVLine(line: string) {
    const result: string[] = [];
    let cur = '';
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
        const char = line[i];
        if (char === '"') {
            inQuotes = !inQuotes;
        } else if (char === ',' && !inQuotes) {
            result.push(cur.trim());
            cur = '';
        } else {
            cur += char;
        }
    }
    result.push(cur.trim());
    return result;
}

async function main() {
    const lines = csvData.split('\n');
    const headers = parseCSVLine(lines[0]);
    const data = lines.slice(1).filter(l => l.trim()).map(line => {
        const values = parseCSVLine(line);
        const obj: any = {};
        headers.forEach((h, i) => {
            let val: any = values[i];
            if (val === 'null') val = null;
            if (val === 'true') val = true;
            if (val === 'false') val = false;
            // founding_year, member_count, ministry_count
            if (['founding_year', 'member_count', 'ministry_count'].includes(h)) {
                val = parseInt(val) || 0;
            }
            obj[h] = val;
        });
        return obj;
    });

    console.log(`Prepared ${data.length} new churches for insertion.`);

    // Chunking to avoid large request payload
    const chunkSize = 50;
    for (let i = 0; i < data.length; i += chunkSize) {
        const chunk = data.slice(i, i + chunkSize);
        const { error } = await supabase
            .from('church_registry')
            .upsert(chunk, { onConflict: 'slug' });
        
        if (error) {
            console.error(`Error inserting chunk ${i / chunkSize}:`, error);
        } else {
            console.log(`Successfully inserted chunk ${i / chunkSize + 1}`);
        }
    }

    const { count } = await supabase
        .from('church_registry')
        .select('*', { count: 'exact', head: true });

    console.log(`Seeding complete. Total churches in database: ${count}`);
}

main().catch(console.error);

