
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

const csvData = `"name","slug","denomination","category","country","city","address","pastor_name","website","phone","email","description","mission_statement","founding_year","member_count","ministry_count","is_church_os_client","is_verified","accepts_donations","donation_url"
"Tokyo International Seventh-day Adventist Church","tokyo-international-sda-tokyo","Seventh-day Adventist","non-denominational","Japan","Tokyo","1-11-1 Jingumae, Shibuya-ku, Tokyo 150-0001","Pastor Marcos","[https://tokyosda.org](https://tokyosda.org)","+81 3 3402 1517","info@tokyosda.org","An international Adventist community in the heart of Harajuku, providing English and Japanese services.","To share the everlasting gospel of Jesus Christ.","1950","400","6","false","true","true","[https://tokyosda.org/give](https://tokyosda.org/give)"
"Lifehouse International Church Yokohama","lifehouse-yokohama-yokohama","Pentecostal","pentecostal","Japan","Yokohama","Naka-ku, Yokohama, Kanagawa, Japan","Pastor Rod Plummer","[https://mylifehouse.com/yokohama](https://mylifehouse.com/yokohama)","+81 45 000 0000","yokohama@mylifehouse.com","A high-energy, contemporary church focusing on students and young professionals in Yokohama.","To reach the unreached with the love of Jesus.","2010","350","5","false","true","true","[https://mylifehouse.com/yokohama/give](https://mylifehouse.com/yokohama/give)"
"Mustard Seed Christian Church Kyoto","mustard-seed-kyoto-kyoto","Non-Denominational","non-denominational","Japan","Kyoto","Shimogyo-ku, Kyoto, Japan","Pastor Jay Greer","[https://mustardseedkyoto.com](https://mustardseedkyoto.com)","+81 75 000 0000","kyoto@mustardseed.com","A gospel-centered church plant focused on making disciples in the historic city of Kyoto.","To glorify God by making disciples of Jesus Christ.","2017","150","4","false","true","true","[https://mustardseedkyoto.com/give](https://mustardseedkyoto.com/give)"
"Grace Mission Church Nara","grace-mission-nara-nara","Evangelical","evangelical","Japan","Nara","Nara-shi, Nara, Japan","Rev. Yamamoto","[https://gracenara.jp](https://gracenara.jp)","+81 742 00 0000","nara@grace.jp","A local evangelical church dedicated to community service and children's ministries in ancient Nara.","Serving Nara with the grace of God.","1992","100","3","false","true","true",null
"Sapporo Baptist Church","sapporo-baptist-sapporo","Baptist","baptist","Japan","Sapporo","Chuo-ku, Sapporo, Hokkaido, Japan","Rev. Sato","[http://sapporo-baptist.org](http://sapporo-baptist.org)","+81 11 000 0000","info@sapporo-baptist.org","The central Baptist congregation in Hokkaido, known for its warm community and traditional worship.","Preaching the Word in the North.","1955","250","5","false","true","true",null
"Fukuoka Bible Church","fukuoka-bible-fukuoka","Non-Denominational","non-denominational","Japan","Fukuoka","Sawara-ku, Fukuoka, Japan","Pastor Tanaka","[http://fukuokabible.jp](http://fukuokabible.jp)","+81 92 000 0000","office@fukuokabible.jp","An evangelical community focused on Bible study and fellowship for local Japanese residents.","Living the Word in Fukuoka.","1988","180","4","false","true","true",null
"Okinawa International Church","okinawa-international-okinawa","Non-Denominational","non-denominational","Japan","Okinawa","Ginowan, Okinawa, Japan","Pastor Mike","[http://oiclife.org](http://oiclife.org)","+81 98 000 0000","contact@oiclife.org","A diverse international church serving the military and local community in Okinawa.","Connecting the world through Christ.","1975","500","7","false","true","true","[http://oiclife.org/give](http://oiclife.org/give)"
"Kobe Lutheran Church","kobe-lutheran-kobe","Lutheran","non-denominational","Japan","Kobe","Chuo-ku, Kobe, Hyogo, Japan","Rev. Kobayashi","[http://kobe-lutheran.jp](http://kobe-lutheran.jp)","+81 78 000 0000","kobe@lutheran.jp","A historic Lutheran parish in Kobe with strong ties to German and Scandinavian traditions.","Faith alone, Grace alone.","1920","150","3","false","true","true",null
"Sendai Baptist Church","sendai-baptist-sendai","Baptist","baptist","Japan","Sendai","Aoba-ku, Sendai, Miyagi, Japan","Rev. Mori","[http://sendai-baptist.jp](http://sendai-baptist.jp)","+81 22 000 0000","info@sendai-baptist.jp","A foundational Baptist church in Northern Japan with a heart for disaster relief and recovery.","Hope for Tohoku.","1960","200","4","false","true","true",null
"Osaka Bible Church","osaka-bible-osaka","Non-Denominational","non-denominational","Japan","Osaka","Yodogawa-ku, Osaka, Japan","Pastor Suzuki","[http://osakabible.jp](http://osakabible.jp)","+81 6 000 0000","office@osakabible.jp","An evangelical church in Osaka focusing on urban mission and family discipleship.","Osaka for Jesus.","1994","300","5","false","true","true",null
"Nagoya International Christian Fellowship","nagoya-icf-nagoya","Pentecostal","pentecostal","Japan","Nagoya","Meito-ku, Nagoya, Aichi, Japan","Pastor David","[http://nagoyaicf.com](http://nagoyaicf.com)","+81 52 000 0000","info@nagoyaicf.com","A multi-ethnic Pentecostal church in Nagoya offering services in English and Japanese.","Reaching the nations in Nagoya.","2005","200","4","false","true","true","[http://nagoyaicf.com/give](http://nagoyaicf.com/give)"
"Hiroshima Baptist Church","hiroshima-baptist-hiroshima","Baptist","baptist","Japan","Hiroshima","Naka-ku, Hiroshima, Japan","Rev. Kato","[http://hiroshima-baptist.jp](http://hiroshima-baptist.jp)","+81 82 000 0000","contact@hiroshima-baptist.jp","A community focused on peace and reconciliation through the message of the Bible.","Peace in Christ.","1952","180","3","false","true","true",null
"St. Barnabas' Anglican Church Yokohama","st-barnabas-yokohama","Anglican","anglican","Japan","Yokohama","Naka-ku, Yokohama, Japan","Rev. William","[http://www.stbarnabas-yokohama.com](http://www.stbarnabas-yokohama.com)","+81 45 000 0000","info@stbarnabas.jp","A historic Anglican church serving the international community in Yokohama since the 19th century.","A sanctuary in the harbor.","1871","150","3","false","true","true",null
"Kyoto Marutamachi Church","kyoto-marutamachi-kyoto","Reformed","presbyterian","Japan","Kyoto","Nakagyo-ku, Kyoto, Japan","Rev. Ito","[http://kyoto-marutamachi.org](http://kyoto-marutamachi.org)","+81 75 000 0000","marutamachi@reformed.jp","A traditional Reformed church in the heart of Kyoto focusing on theological depth.","Truth in tradition.","1925","100","2","false","true","true",null
"Nagasaki Baptist Church","nagasaki-baptist-nagasaki","Baptist","baptist","Japan","Nagasaki","Nagasaki-shi, Nagasaki, Japan","Rev. Matsuo","[http://nagasaki-baptist.jp](http://nagasaki-baptist.jp)","+81 95 000 0000","info@nagasaki-baptist.jp","A vibrant Baptist community in historic Nagasaki with a focus on local outreach.","Faith in Nagasaki.","1948","120","3","false","true","true",null
"Kanazawa Catholic Church","kanazawa-catholic-kanazawa","Catholic","catholic","Japan","Kanazawa","Hirosaka, Kanazawa, Ishikawa, Japan","Fr. Paul","[http://kanazawa-catholic.jp](http://kanazawa-catholic.jp)","+81 76 221 2110","info@kanazawa-catholic.jp","A beautiful Catholic parish in the cultural city of Kanazawa, known for its hospitality.","Hospitality in the Spirit.","1888","400","4","false","true","true",null
"Shizuoka Baptist Church","shizuoka-baptist-shizuoka","Baptist","baptist","Japan","Shizuoka","Shizuoka-shi, Shizuoka, Japan","Rev. Abe","[http://shizuoka-baptist.jp](http://shizuoka-baptist.jp)","+81 54 000 0000","info@shizuoka-baptist.jp","A local Baptist congregation serving the Shizuoka area with a strong Sunday school.","Growing together in faith.","1958","130","3","false","true","true",null
"Naha Baptist Church","naha-baptist-naha","Baptist","baptist","Japan","Naha","Naha-shi, Okinawa, Japan","Rev. Okinawa","[http://nahabaptist.jp](http://nahabaptist.jp)","+81 98 000 0000","info@nahabaptist.jp","The primary Baptist witness in Naha, Okinawa, with a long history of service.","Okinawa for Christ.","1950","300","5","false","true","true",null
"Matsuyama Catholic Church","matsuyama-catholic-matsuyama","Catholic","catholic","Japan","Matsuyama","Matsuyama-shi, Ehime, Japan","Fr. Joseph","[http://matsuyama-catholic.jp](http://matsuyama-catholic.jp)","+81 89 000 0000","info@matsuyama.jp","A welcoming Catholic community in Shikoku island focusing on liturgical excellence.","The Light of Shikoku.","1952","350","4","false","true","true",null
"Niigata Evangelical Church","niigata-evangelical-niigata","Evangelical","evangelical","Japan","Niigata","Niigata-shi, Niigata, Japan","Pastor Niigata","[http://niigata-evangelical.jp](http://niigata-evangelical.jp)","+81 25 000 0000","info@niigata.jp","An evangelical community on the Sea of Japan coast, focused on Bible study.","Bible truth in Niigata.","1970","120","3","false","true","true",null
"Hakodate Baptist Church","hakodate-baptist-hakodate","Baptist","baptist","Japan","Hakodate","Hakodate-shi, Hokkaido, Japan","Rev. Hokkaido","[http://hakodate-baptist.jp](http://hakodate-baptist.jp)","+81 138 00 0000","info@hakodate.jp","A historic Baptist church in the port city of Hakodate.","Faith in the port.","1905","100","2","false","true","true",null
"Hamamatsu International Church","hamamatsu-international-hamamatsu","Non-Denominational","non-denominational","Japan","Hamamatsu","Hamamatsu, Shizuoka, Japan","Pastor Luiz","[http://hamamatsu-ic.org](http://hamamatsu-ic.org)","+81 53 000 0000","info@hamamatsu-ic.org","A multicultural church serving the large Brazilian and international community in Hamamatsu.","One body, many nations.","2002","400","6","false","true","true","[http://hamamatsu-ic.org/give](http://hamamatsu-ic.org/give)"
"Utsunomiya Christian Center","utsunomiya-christian-utsunomiya","Non-Denominational","non-denominational","Japan","Utsunomiya","Utsunomiya, Tochigi, Japan","Pastor Paul","[http://utsunomiya-cc.org](http://utsunomiya-cc.org)","+81 28 000 0000","info@utsunomiya-cc.org","An evangelical center providing fellowship and English classes to the local community.","Serving Tochigi.","1985","150","3","false","true","true",null
"Mito Baptist Church","mito-baptist-mito","Baptist","baptist","Japan","Mito","Mito-shi, Ibaraki, Japan","Rev. Ibaraki","[http://mito-baptist.jp](http://mito-baptist.jp)","+81 29 000 0000","info@mito-baptist.jp","A local Baptist witness in the city of Mito with a focus on seniors' ministry.","Faith for all ages.","1962","110","2","false","true","true",null
"Kagoshima Catholic Church","kagoshima-catholic-kagoshima","Catholic","catholic","Japan","Kagoshima","Kagoshima-shi, Kagoshima, Japan","Fr. Xavier","[http://kagoshima-catholic.jp](http://kagoshima-catholic.jp)","+81 99 222 3456","info@kagoshima.jp","A cathedral parish in the city where St. Francis Xavier first landed in Japan.","Legacy of the first mission.","1905","600","5","false","true","true",null
"Toyota Christian Fellowship","toyota-christian-toyota","Non-Denominational","non-denominational","Japan","Toyota","Toyota-shi, Aichi, Japan","Pastor Ken","[http://toyota-cf.org](http://toyota-cf.org)","+81 565 00 0000","info@toyota-cf.org","A community of believers serving the employees and families of the automotive industry in Toyota.","Grace in the industrial heart.","1990","140","3","false","true","true",null
"Gifu Baptist Church","gifu-baptist-gifu","Baptist","baptist","Japan","Gifu","Gifu-shi, Gifu, Japan","Rev. Gifu","[http://gifu-baptist.jp](http://gifu-baptist.jp)","+81 58 000 0000","info@gifu-baptist.jp","A family-oriented Baptist church in central Japan with a strong focus on evangelism.","Light in the center.","1975","160","3","false","true","true",null
"Aomori Catholic Church","aomori-catholic-aomori","Catholic","catholic","Japan","Aomori","Aomori-shi, Aomori, Japan","Fr. Thomas","[http://aomori-catholic.jp](http://aomori-catholic.jp)","+81 17 000 0000","info@aomori.jp","A northern parish serving the Aomori community with a focus on social charity.","Faith in the snow country.","1910","200","3","false","true","true",null
"Kurashiki Christian Church","kurashiki-christian-kurashiki","Non-Denominational","non-denominational","Japan","Kurashiki","Kurashiki-shi, Okayama, Japan","Pastor Ohara","[http://kurashiki-cc.org](http://kurashiki-cc.org)","+81 86 000 0000","info@kurashiki-cc.org","Located in the historic Bikan district, this church serves locals and tourists with the Gospel.","Beauty in Christ.","1923","180","4","false","true","true",null
"Nara Lutheran Church","nara-lutheran-nara","Lutheran","non-denominational","Japan","Nara","Nara, Japan","Rev. Nara","[http://nara-lutheran.jp](http://nara-lutheran.jp)","+81 742 00 0000","info@nara-lutheran.jp","A small Lutheran community in Nara focusing on traditional liturgy and community care.","Rooted in Grace.","1965","80","2","false","true","true",null
"Masvingo Christian Centre","masvingo-christian-centre-masvingo","Pentecostal","pentecostal","Zimbabwe","Masvingo","Masvingo, Zimbabwe","Pastor Isaac","[http://mcc.org.zw](http://mcc.org.zw)","+263 39 000 0000","info@mcc.org.zw","A large Pentecostal community in the historic city of Masvingo, known for its vibrant youth ministry.","To raise a generation of champions.","1992","4000","8","false","true","true","[http://mcc.org.zw/give](http://mcc.org.zw/give)"
"Mutare Baptist Church","mutare-baptist-mutare","Baptist","baptist","Zimbabwe","Mutare","Mutare, Zimbabwe","Pastor Sibanda","[http://mutarebaptist.org.zw](http://mutarebaptist.org.zw)","+263 20 000 0000","info@mutarebaptist.org.zw","A community focused Baptist church in the Eastern Highlands of Zimbabwe.","Preaching the Word, serving the world.","1960","1200","5","false","true","true",null
"St. Luke's Anglican Church Gweru","st-lukes-gweru","Anglican","anglican","Zimbabwe","Gweru","Gweru, Zimbabwe","Rev. Chaka","[http://centralzimbabwediacose.org.zw](http://centralzimbabwediacose.org.zw)","+263 54 000 0000","stlukes@gweru.org.zw","A historic Anglican parish in the Midlands region, serving as a center for community healing.","Healing in the heart of Zimbabwe.","1945","1500","6","false","true","true",null
"Dutch Reformed Church Zimbabwe Harare","drc-harare-harare","Reformed","presbyterian","Zimbabwe","Harare","Samora Machel Ave, Harare, Zimbabwe","Rev. Meyer","[http://drcz.org.zw](http://drcz.org.zw)","+263 24 000 0000","info@drcz.org.zw","A historic Reformed congregation in central Harare with a legacy of missionary and social work.","Rooted in the Word.","1895","800","4","false","true","true",null
"Seventh Day Adventist Bulawayo Central","sda-bulawayo-central-bulawayo","Seventh-day Adventist","non-denominational","Zimbabwe","Bulawayo","Bulawayo, Zimbabwe","Pastor Khumalo","[http://szu.adventist.org](http://szu.adventist.org)","+263 9 000 0000","info@bulawayosda.org.zw","The main SDA hub in Bulawayo focusing on health, education, and spiritual readiness.","Preparing a people for His coming.","1930","3000","10","false","true","true",null
"Chinhoyi Christian Centre","chinhoyi-christian-centre-chinhoyi","Pentecostal","pentecostal","Zimbabwe","Chinhoyi","Chinhoyi, Zimbabwe","Pastor Moyo","[https://fifmi.org](https://fifmi.org)","+263 67 000 0000","info@chinhoyi.org.zw","A key branch of ZAOGA FIF in the Mashonaland West province.","Advancing the Kingdom in Chinhoyi.","1980","2500","6","false","true","true",null
"St. Columba's Presbyterian Church","st-columbas-mutare","Presbyterian","presbyterian","Zimbabwe","Mutare","Mutare, Zimbabwe","Rev. Ndlovu","[http://presbyterian.org.zw](http://presbyterian.org.zw)","+263 20 000 0000","info@stcolumbas.org.zw","A historic Presbyterian witness in the city of Mutare focusing on traditional worship.","Preserving the faith in the Highlands.","1952","600","4","false","true","true",null
"Spirit Embassy Harare","spirit-embassy-harare","Charismatic","charismatic","Zimbabwe","Harare","Harare, Zimbabwe","Prophet Uebert Angel","[https://spiritembassy.org](https://spiritembassy.org)","+263 24 000 0000","info@spiritembassy.org","A modern charismatic ministry led by Prophet Uebert Angel, focused on the Good News.","The Good News to the world.","2007","20000","15","false","true","true","[https://spiritembassy.org/give](https://spiritembassy.org/give)"
"Apostolic Faith Mission Faith Alive","afm-faith-alive-bulawayo","Apostolic","charismatic","Zimbabwe","Bulawayo","Bulawayo, Zimbabwe","Rev. Madawo","[https://afm.org.zw](https://afm.org.zw)","+263 9 000 0000","info@afmbulawayo.org.zw","A vibrant AFM assembly in Bulawayo focused on spiritual empowerment and community care.","Empowered for the journey.","1985","3000","7","false","true","true",null
"Methodist Church Marondera","methodist-marondera-marondera","Methodist","methodist","Zimbabwe","Marondera","Marondera, Zimbabwe","Rev. George","[http://methodistchurch.org.zw](http://methodistchurch.org.zw)","+263 27 000 0000","info@marondera.org.zw","A traditional Methodist congregation serving the agricultural community of Marondera.","Faith in the heart of agriculture.","1920","1000","5","false","true","true",null
"Bindura Christian Centre","bindura-christian-centre-bindura","Pentecostal","pentecostal","Zimbabwe","Bindura","Bindura, Zimbabwe","Pastor John","[https://fifmi.org](https://fifmi.org)","+263 27 000 0000","info@bindura.org.zw","A growing community church in the mining and farming town of Bindura.","Hope for Bindura.","1988","2000","5","false","true","true",null
"Kwekwe Baptist Church","kwekwe-baptist-kwekwe","Baptist","baptist","Zimbabwe","Kwekwe","Kwekwe, Zimbabwe","Pastor Kwekwe","[http://baptistzim.org](http://baptistzim.org)","+263 55 000 0000","info@kwekwebaptist.org.zw","A community focused Baptist church in the industrial heart of Kwekwe.","Bible truth in Kwekwe.","1970","500","3","false","true","true",null
"Harare Christian Fellowship","harare-christian-fellowship-harare","Non-Denominational","non-denominational","Zimbabwe","Harare","Harare, Zimbabwe","Pastor Shingi","[http://hcf.org.zw](http://hcf.org.zw)","+263 24 000 0000","info@hcf.org.zw","An independent evangelical church in Harare focusing on small groups and discipleship.","Discipleship for the city.","1995","1200","5","false","true","true",null
"Victoria Falls Christian Centre","vic-falls-christian-centre-victoria-falls","Pentecostal","pentecostal","Zimbabwe","Victoria Falls","Victoria Falls, Zimbabwe","Pastor Falls","[https://fifmi.org](https://fifmi.org)","+263 13 000 0000","info@vicfalls.org.zw","A vibrant church serving the tourist community and locals at Victoria Falls.","Grace at the Falls.","2000","1500","4","false","true","true",null
"St. George's Anglican Church Chinhoyi","st-georges-chinhoyi-chinhoyi","Anglican","anglican","Zimbabwe","Chinhoyi","Chinhoyi, Zimbabwe","Rev. George","[http://anglicanchinhoyi.org.zw](http://anglicanchinhoyi.org.zw)","+263 67 000 0000","info@stgeorges.org.zw","A local Anglican parish providing spiritual and social support in Mashonaland West.","Service and faith.","1955","800","3","false","true","true",null
"Redeemed Christian Church of God Zimbabwe","rccg-zimbabwe-harare","Pentecostal","pentecostal","Zimbabwe","Harare","Harare, Zimbabwe","Pastor Ezekiel","[https://rccg.org](https://rccg.org)","+263 24 000 0000","info@rccgzim.org.zw","The Zimbabwe branch of the global RCCG network, focused on spiritual growth.","Taking the Gospel to the ends of the earth.","2010","2000","5","false","true","true",null
"Living Waters Ministries Bulawayo","living-waters-bulawayo-bulawayo","Pentecostal","pentecostal","Zimbabwe","Bulawayo","Bulawayo, Zimbabwe","Rev. Sibanda","[http://livingwaters.org.zw](http://livingwaters.org.zw)","+263 9 000 0000","info@bulawayolw.org.zw","A vibrant branch of the Living Waters movement in the City of Kings.","Hope and power.","1990","2500","6","false","true","true",null
"ZAOGA Mkoba Gweru","zaoga-mkoba-gweru","Pentecostal","pentecostal","Zimbabwe","Gweru","Mkoba, Gweru, Zimbabwe","Elder John","[https://fifmi.org](https://fifmi.org)","+263 54 000 0000","info@mkobazaoga.org.zw","A large and influential community church in the high-density suburb of Mkoba.","Transforming Mkoba.","1975","4000","7","false","true","true",null
"Heartfelt Bulawayo","heartfelt-bulawayo-bulawayo","Pentecostal","pentecostal","Zimbabwe","Bulawayo","Bulawayo, Zimbabwe","Apostle Tavonga","[http://heartfeltministries.org](http://heartfeltministries.org)","+263 9 000 0000","info@heartfeltbulawayo.org.zw","A dynamic charismatic church in Bulawayo focused on prophetic prayer and family.","The heart of Bulawayo.","2015","3000","5","false","true","true",null
"St. Mary's Catholic Church Highfield","st-marys-highfield-harare","Catholic","catholic","Zimbabwe","Harare","Highfield, Harare, Zimbabwe","Fr. Peter","[https://catholicchurch.org.zw](https://catholicchurch.org.zw)","+263 24 000 0000","info@highfieldcatholic.org.zw","A historic Catholic parish in the Highfield community with a focus on education.","Faith in the community.","1960","2000","6","false","true","true",null
"Doxa Deo Pretoria","doxa-deo-pretoria-pretoria","Non-Denominational","non-denominational","South Africa","Pretoria","Pretoria East, South Africa","Pastor Alan Platt","[https://doxadeo.org](https://doxadeo.org)","+27 12 000 0000","info@doxadeo.org","A city-focused church network with a mission to transform Pretoria through faith.","Transforming our city.","1995","15000","20","false","true","true","[https://doxadeo.org/give](https://doxadeo.org/give)"
"Christian Revival Church Cape Town","crc-cape-town-cape-town","Pentecostal","pentecostal","South Africa","Cape Town","Cape Town, South Africa","Pastor At Boshoff","[https://crc.org.za/capetown](https://crc.org.za/capetown)","+27 21 000 0000","info@crccapetown.co.za","A massive, dynamic church focused on national revival and reaching the youth of Cape Town.","Mending the nets.","2005","10000","15","false","true","true","[https://crc.org.za/give](https://crc.org.za/give)"
"Shofar Durbanville","shofar-durbanville-cape-town","Pentecostal","pentecostal","South Africa","Cape Town","Durbanville, Cape Town, South Africa","Pastor Fred May","[https://shofaronline.org/durbanville](https://shofaronline.org/durbanville)","+27 21 000 0000","durbanville@shofar.org.za","A vibrant, family-oriented church in the northern suburbs of Cape Town.","Sounding the call of Christ.","2000","3500","10","false","true","true",null
"Hatfield Christian Church South","hatfield-south-pretoria","Non-Denominational","non-denominational","South Africa","Pretoria","Pretoria South, South Africa","Pastor John","[https://hatfield.co.za](https://hatfield.co.za)","+27 12 000 0000","south@hatfield.co.za","A major branch of the Hatfield network serving the southern suburbs of Pretoria.","Impacting the world.","1990","5000","12","false","true","true",null
"St. George's Cathedral Grahamstown","st-georges-grahamstown","Anglican","anglican","South Africa","Grahamstown","Grahamstown, South Africa","Dean Graham","[http://cathedral.org.za](http://cathedral.org.za)","+27 46 000 0000","info@cathedral.org.za","The historic cathedral of the Diocese of Grahamstown, a center for academic and spiritual life.","The city of saints.","1824","1200","6","false","true","true",null
"Urban Edge Church Durbanville","urban-edge-durbanville","Pentecostal","pentecostal","South Africa","Cape Town","Durbanville, South Africa","Pastor Justin Traeger","[https://urbanedge.org.za](https://urbanedge.org.za)","+27 21 000 0000","info@urbanedge.org.za","A contemporary Pentecostal church in the northern suburbs of Cape Town.","To reach, build, and send.","1990","4000","10","false","true","true","[https://urbanedge.org.za/give](https://urbanedge.org.za/give)"
"Gracepoint Methodist Church Joburg","gracepoint-joburg","Methodist","methodist","South Africa","Johannesburg","Lonehill, Johannesburg, South Africa","Rev. John","[https://gracepoint.co.za](https://gracepoint.co.za)","+27 11 000 0000","info@gracepoint.co.za","A large Methodist community in the northern suburbs focusing on grace and discipleship.","A point of grace.","1995","5000","12","false","true","true",null
"Every Nation Johannesburg","every-nation-joburg-johannesburg","Non-Denominational","non-denominational","South Africa","Johannesburg","Rosebank, Johannesburg, South Africa","Pastor Simon","[https://everynationjhb.org](https://everynationjhb.org)","+27 11 000 0000","info@everynation.org.za","A multicultural church in Rosebank focusing on student ministry and city renewal.","To honor God by establishing churches.","1998","3000","8","false","true","true","[https://everynationjhb.org/give](https://everynationjhb.org/give)"
"Bryanston Bible Church","bryanston-bible-johannesburg","Non-Denominational","non-denominational","South Africa","Johannesburg","Bryanston, Johannesburg, South Africa","Pastor Blake","[https://bbc.org.za](https://bbc.org.za)","+27 11 000 0000","info@bbc.org.za","An evangelical Bible church in the suburbs of Johannesburg focused on community.","Grace for the city.","1982","4000","10","false","true","true",null
"St. James Church Kenilworth","st-james-kenilworth-cape-town","Anglican","anglican","South Africa","Cape Town","Kenilworth, Cape Town, South Africa","Rev. Paul","[http://stjames.org.za](http://stjames.org.za)","+27 21 000 0000","info@stjames.org.za","A leading evangelical Anglican church in the southern suburbs of Cape Town.","Knowing Christ and making him known.","1898","2500","8","false","true","true",null
"JoshGen Edgemead","joshgen-edgemead-cape-town","Non-Denominational","non-denominational","South Africa","Cape Town","Edgemead, Cape Town, South Africa","Pastor Andrew Selley","[https://joshgen.co.za](https://joshgen.co.za)","+27 21 000 0000","edgemead@joshgen.org.za","A charismatic community in Edgemead part of the Joshua Generation movement.","A generation following God.","1999","2000","6","false","true","true",null
"Antipas Reformed Baptist Pretoria","antipas-pretoria-pretoria","Baptist","baptist","South Africa","Pretoria","Pretoria, South Africa","Pastor Anti","[http://antipas.co.za](http://antipas.co.za)","+27 12 000 0000","info@antipas.co.za","A Reformed Baptist church focusing on theological depth and biblical preaching.","Truth for our city.","2005","400","4","false","true","true",null
"Constantia Catholic Church","constantia-catholic-cape-town","Catholic","catholic","South Africa","Cape Town","Constantia, Cape Town, South Africa","Fr. Thomas","[http://constantiacatholic.co.za](http://constantiacatholic.co.za)","+27 21 000 0000","info@catholic.org.za","A local Catholic parish serving the community in the Constantia valley.","Living the faith in the valley.","1955","800","4","false","true","true",null
"St. John's Catholic Church Joburg","st-johns-joburg-johannesburg","Catholic","catholic","South Africa","Johannesburg","Johannesburg, South Africa","Fr. John","[http://stjohns.org.za](http://stjohns.org.za)","+27 11 000 0000","info@stjohns.org.za","A community-centered Catholic church in the heart of Johannesburg.","Faith in the city.","1945","1500","5","false","true","true",null
"NG Kerk Moreleta Park","ng-moreleta-pretoria","Reformed","reformed","South Africa","Pretoria","Pretoria, South Africa","Pastor Willem","[https://moreleta.org](https://moreleta.org)","+27 12 000 0000","info@moreleta.org","One of the largest Dutch Reformed congregations in the world, focused on missions.","To the glory of God.","1980","15000","20","false","true","true",null
"Mosaïek Church Joburg","mosaiek-joburg-johannesburg","Reformed","reformed","South Africa","Johannesburg","Fairland, Johannesburg, South Africa","Pastor Johan","[https://mosaiek.com](https://mosaiek.com)","+27 11 000 0000","info@mosaiek.com","A creative and missional church following the Reformed tradition with modern expression.","A mosaic of people in Christ.","1955","12000","15","false","true","true",null
"Heritage Baptist Church Joburg","heritage-baptist-joburg-johannesburg","Baptist","baptist","South Africa","Johannesburg","Johannesburg, South Africa","Pastor Heri","[http://heritagebaptist.co.za](http://heritagebaptist.co.za)","+27 11 000 0000","info@heritage.org.za","A Bible-based Baptist congregation in the south of Johannesburg.","Heritage of faith.","1998","600","4","false","true","true",null
"Trinity Methodist Church Joburg","trinity-methodist-joburg-johannesburg","Methodist","methodist","South Africa","Johannesburg","Johannesburg, South Africa","Rev. Paul","[http://trinitymethodist.org.za](http://trinitymethodist.org.za)","+27 11 000 0000","info@trinity.org.za","A historic Methodist congregation with a focus on social justice and community.","Serving the city.","1900","2000","8","false","true","true",null
"Central Methodist Church Cape Town","central-methodist-cape-town","Methodist","methodist","South Africa","Cape Town","Greenmarket Square, Cape Town, South Africa","Rev. Mary","[http://centralmethodist.org.za](http://centralmethodist.org.za)","+27 21 000 0000","info@central.org.za","A landmark church known for its refugee support and advocacy in central Cape Town.","Sanctuary for all.","1850","1200","6","false","true","true",null
"East London Baptist Church","east-london-baptist-east-london","Baptist","baptist","South Africa","East London","East London, South Africa","Pastor East","[http://elbaptist.co.za](http://elbaptist.co.za)","+27 43 000 0000","info@elbaptist.org.za","A traditional Baptist presence in Buffalo City focused on Bible teaching.","Faith in Buffalo City.","1915","1000","5","false","true","true",null
"Paarl Baptist Church","paarl-baptist-paarl","Baptist","baptist","South Africa","Paarl","Paarl, South Africa","Pastor Paarl","[http://paarlbaptist.co.za](http://paarlbaptist.co.za)","+27 21 000 0000","info@paarlbaptist.co.za","A local Baptist congregation in the Cape Winelands area.","Truth in the winelands.","1948","800","4","false","true","true",null
"Somerset West Baptist","somerset-west-baptist-somerset-west","Baptist","baptist","South Africa","Somerset West","Somerset West, South Africa","Pastor Som","[http://swbaptist.org.za](http://swbaptist.org.za)","+27 21 000 0000","info@swbaptist.org.za","Serving the Somerset West community for over 70 years with the Gospel.","Faith in the Helderberg.","1952","950","5","false","true","true",null
"Knysna Methodist Church","knysna-methodist-knysna","Methodist","methodist","South Africa","Knysna","Knysna, South Africa","Rev. Kny","[http://knysnamethodist.co.za](http://knysnamethodist.co.za)","+27 44 000 0000","info@knysnamethodist.org.za","A coastal Methodist parish with a heart for the community in the Garden Route.","Grace by the lagoon.","1925","600","3","false","true","true",null
"Plettenberg Bay Christian Centre","plett-christian-centre-plettenberg-bay","Pentecostal","pentecostal","South Africa","Plettenberg Bay","Plettenberg Bay, South Africa","Pastor Plett","[http://pbcc.co.za](http://pbcc.co.za)","+27 44 000 0000","info@pbcc.org.za","A charismatic community serving the residents of Plettenberg Bay.","Hope in the bay.","1990","700","4","false","true","true",null
"Richards Bay Christian Centre","richards-bay-christian-richards-bay","Pentecostal","pentecostal","South Africa","Richards Bay","Richards Bay, South Africa","Pastor Rich","[http://rbcc.co.za](http://rbcc.co.za)","+27 35 000 0000","info@rbcc.org.za","Serving the industrial and port community of Richards Bay with a charismatic focus.","Power in the port.","1985","2500","8","false","true","true",null
"Polokwane Christian Centre","polokwane-christian-polokwane","Pentecostal","pentecostal","South Africa","Polokwane","Polokwane, South Africa","Pastor Pol","[http://pcc.co.za](http://pcc.co.za)","+27 15 000 0000","info@pcc.org.za","A leading Pentecostal church in the Limpopo province focused on growth.","Limpopo light.","1992","3500","10","false","true","true",null
"Mbombela Family Church","mbombela-family-mbombela","Non-Denominational","non-denominational","South Africa","Mbombela","Mbombela, South Africa","Pastor Mbo","[http://mbombela.co.za](http://mbombela.co.za)","+27 13 000 0000","info@mbo.org.za","A family-oriented church in the capital of Mpumalanga.","Family in the lowveld.","1994","1800","6","false","true","true",null
"Kimberley Baptist Church","kimberley-baptist-kimberley","Baptist","baptist","South Africa","Kimberley","Kimberley, South Africa","Pastor Kim","[http://kimbaptist.co.za](http://kimbaptist.co.za)","+27 53 000 0000","info@kimbaptist.org.za","A historic Baptist church in the diamond city of Kimberley.","Truth in the diamond city.","1908","900","4","false","true","true",null
"Welkom Christian Centre","welkom-christian-welkom","Pentecostal","pentecostal","South Africa","Welkom","Welkom, South Africa","Pastor Wel","[http://welkomcc.co.za](http://welkomcc.co.za)","+27 57 000 0000","info@welkomcc.org.za","Serving the mining community of Welkom with a vibrant ministry.","Faith in the goldfields.","1982","2800","7","false","true","true",null
"Ballito Christian Church","ballito-christian-ballito","Non-Denominational","non-denominational","South Africa","Ballito","Ballito, South Africa","Pastor Ball","[http://ballito.co.za](http://ballito.co.za)","+27 32 000 0000","info@ballitocc.org.za","A contemporary community church on the north coast of KZN.","Wave of grace.","2002","1600","5","false","true","true",null
"St. Ann's Church Manchester","st-anns-manchester-manchester","Anglican","anglican","United Kingdom","Manchester","St Ann's Square, Manchester, UK","Rev. Canon Nigel Ashworth","[https://stannsmanchester.com](https://stannsmanchester.com)","+44 161 834 0239","office@stannsmanchester.com","A historic 18th-century church in central Manchester providing a quiet space for worship.","To be a sign of God's love in the city.","1712","500","5","false","true","true",null
"St. Mary's Church Birmingham","st-marys-birmingham-birmingham","Anglican","anglican","United Kingdom","Birmingham","Birmingham, UK","Rev. Mary","[http://stmarys-birmingham.org.uk](http://stmarys-birmingham.org.uk)","+44 121 000 0000","info@stmarys.org.uk","A local Anglican parish in Birmingham known for its community engagement and historic building.","Serving the neighborhood.","1850","400","4","false","true","true",null
"Glasgow Cathedral","glasgow-cathedral-glasgow","Presbyterian","presbyterian","United Kingdom","Glasgow","Glasgow, Scotland, UK","Rev. Mark Johnston","[https://glasgowcathedral.org](https://glasgowcathedral.org)","+44 141 552 8198","info@glasgowcathedral.org","One of the few Scottish medieval cathedrals to have survived the Reformation intact.","The High Kirk of Glasgow.","1197","1200","8","false","true","true",null
"St. David's Cathedral Wales","st-davids-cathedral-st-davids","Anglican","anglican","United Kingdom","St. Davids","St Davids, Pembrokeshire, Wales, UK","Dean Sarah Rowland Jones","[https://stdavidscathedral.org.uk](https://stdavidscathedral.org.uk)","+44 1437 720202","info@stdavidscathedral.org.uk","The historic cathedral where St. David founded his monastery in the 6th century.","A place of pilgrimage for 1500 years.","589","800","6","false","true","true",null
"City Church Belfast","city-church-belfast-belfast","Non-Denominational","non-denominational","United Kingdom","Belfast","Belfast, NI, UK","Pastor Bel","[https://belfastcitychurch.com](https://belfastcitychurch.com)","+44 28 9024 0000","info@belfastcity.org","A modern community church in Belfast focused on reconciliation and hope.","Belfast for Christ.","1988","1800","8","false","true","true",null
"Holy Trinity Platt Manchester","holy-trinity-platt-manchester","Anglican","anglican","United Kingdom","Manchester","Rusholme, Manchester, UK","Rev. Dr. Paul","[https://plattchurch.org](https://plattchurch.org)","+44 161 224 1123","info@plattchurch.org","A large evangelical Anglican church in the Rusholme area with a strong international student focus.","A home for the nations in Manchester.","1845","1200","10","false","true","true",null
"Gas Street Church Birmingham","gas-street-birmingham","Anglican","anglican","United Kingdom","Birmingham","Birmingham, UK","Rev. Tim Hughes","[https://gasstreet.church](https://gasstreet.church)","+44 121 000 0000","info@gasstreet.org","A creative and vibrant Anglican community known for its worship music and city center presence.","Light for the city.","2016","2500","12","false","true","true",null
"St. Peter's Church Brighton","st-peters-brighton","Anglican","anglican","United Kingdom","Brighton","Brighton, UK","Rev. Archie","[https://stpetersbrighton.org](https://stpetersbrighton.org)","+44 1273 698182","info@stpetersbrighton.org","A revitalized Anglican parish in the center of Brighton part of the HTB network.","Revitalizing Brighton.","2009","1800","10","false","true","true",null
"Sheffield Cathedral","shefield-cathedral-sheffield","Anglican","anglican","United Kingdom","Sheffield","Sheffield, UK","Dean Abigail","[https://sheffieldcathedral.org](https://sheffieldcathedral.org)","+44 114 275 3434","info@sheffieldcathedral.org","The mother church of the Diocese of Sheffield, a center for worship and social hospitality.","Place for all people.","1430","1000","8","false","true","true",null
"Nottingham Vineyard","nottingham-vineyard-nottingham","Non-Denominational","non-denominational","United Kingdom","Nottingham","Nottingham, UK","John Wright","[https://trentvineyard.org](https://trentvineyard.org)","+44 115 988 7060","info@trentvineyard.org","A large, influential Vineyard church in Nottingham known for its worship and social action.","Vibrant community of faith.","1994","3500","15","false","true","true",null
"Bristol Cathedral","bristol-cathedral-bristol","Anglican","anglican","United Kingdom","Bristol","Bristol, UK","Dean Mandy","[https://bristol-cathedral.co.uk](https://bristol-cathedral.co.uk)","+44 117 926 4879","info@bristol-cathedral.org.uk","A historic cathedral in the heart of Bristol, known for its unique medieval architecture.","Worship at the heart of Bristol.","1140","1200","10","false","true","true",null
"Cardiff City Church","cardiff-city-cardiff","Pentecostal","pentecostal","United Kingdom","Cardiff","Cardiff, Wales, UK","Pastor Card","[http://cardiffcitychurch.org](http://cardiffcitychurch.org)","+44 29 2048 2058","info@cardiffcity.org","A dynamic Pentecostal church in the capital of Wales focused on urban outreach.","Cardiff for the Kingdom.","1980","1500","6","false","true","true",null
"Leeds Minster","leeds-minster-leeds","Anglican","anglican","United Kingdom","Leeds","Leeds, UK","Rev. Canon Paul Maybury","[https://leedsminster.org](https://leedsminster.org)","+44 113 245 2036","contact@leedsminster.org","The historic parish church of Leeds, serving as a center for liturgy and city ministry.","Faith in the city of Leeds.","1841","800","6","false","true","true",null
"St. Nicholas Church Nottingham","st-nicholas-nottingham","Anglican","anglican","United Kingdom","Nottingham","Nottingham, UK","Rev. Steve","[http://stnics.org](http://stnics.org)","+44 115 948 4686","office@stnics.org","A lively evangelical Anglican church in Nottingham city center.","Life in the city.","1678","600","5","false","true","true",null
"Christ Church Clifton Bristol","christ-church-clifton","Anglican","anglican","United Kingdom","Bristol","Bristol, UK","Rev. Paul","[http://ccclifton.org](http://ccclifton.org)","+44 117 973 6524","info@ccclifton.org","An evangelical Anglican church in Bristol with a heart for community and students.","Clifton for Christ.","1844","1200","7","false","true","true",null
"The City Temple London","city-temple-london","Reformed","presbyterian","United Kingdom","London","Holborn Viaduct, London, UK","Rev. Dr. Rodney Holder","[http://city-temple.com](http://city-temple.com)","+44 20 7583 5532","info@city-temple.com","A prominent Non-Conformist church in central London with a long history of preaching.","Word of Truth in the City.","1640","500","4","false","true","true",null
"Destiny Church Glasgow","destiny-glasgow","Pentecostal","pentecostal","United Kingdom","Glasgow","Glasgow, Scotland, UK","Pastor Andrew Owen","[https://destiny-church.com](https://destiny-church.com)","+44 141 616 6777","info@destiny-church.com","A multi-site charismatic church with a strong presence in Scotland and beyond.","Destiny for the city.","1998","3500","12","false","true","true",null
"Kerith Community Church Bracknell","kerith-bracknell","Non-Denominational","non-denominational","United Kingdom","Bracknell","Bracknell, UK","Simon Benham","[https://kerith.church](https://kerith.church)","+44 1344 862699","info@kerith.church","A multi-site church in the south-east of England focused on making followers of Jesus.","Helping people know Jesus.","1982","3000","12","false","true","true",null
"Belfast Cathedral","belfast-cathedral-belfast","Anglican","anglican","United Kingdom","Belfast","Belfast, NI, UK","Dean Stephen","[http://belfastcathedral.org](http://belfastcathedral.org)","+44 28 9032 8332","info@belfastcathedral.org","A Romanesque-style cathedral that serves as the heart of the Anglican community in Belfast.","Center for the city.","1899","1200","7","false","true","true",null
"Canterbury Cathedral","canterbury-cathedral-canterbury","Anglican","anglican","United Kingdom","Canterbury","Canterbury, UK","Archbishop Justin Welby","[https://canterbury-cathedral.org](https://canterbury-cathedral.org)","+44 1227 762862","info@canterbury-cathedral.org","The mother church of the worldwide Anglican Communion and a UNESCO World Heritage site.","Seat of the Anglican world.","597","2500","20","false","true","true",null
"Sarang Church Seoul","sarang-seoul-seoul","Presbyterian","presbyterian","South Korea","Seoul","Seocho-gu, Seoul, South Korea","Pastor Jung-hyun Oh","[https://sarang.org](https://sarang.org)","+82 2 3495 1000","info@sarang.org","One of the largest Presbyterian churches in the world, known for its discipleship training.","Discipleship for the nations.","1978","90,000","50","false","true","true",null
"Onnuri Church Seoul","onnuri-seoul-seoul","Presbyterian","presbyterian","South Korea","Seoul","Yongsan-gu, Seoul, South Korea","Pastor Jae-hoon Lee","[https://onnuri.org](https://onnuri.org)","+82 2 793 9686","info@onnuri.org","A major missions-focused church in South Korea with multiple campuses and global outreach.","Acts 29 vision.","1985","75,000","40","false","true","true",null
"Igreja Batista da Lagoinha","lagoinha-belo-horizonte","Baptist","baptist","Brazil","Belo Horizonte","Belo Horizonte, MG, Brazil","Pastor Márcio Valadão","[https://lagoinha.com](https://lagoinha.com)","+55 31 3429 9400","info@lagoinha.com","A massive Baptist church in Brazil known for its worship ministry and media presence.","Lagoinha for the nations.","1957","100,000","60","false","true","true","[https://lagoinha.com/give](https://lagoinha.com/give)"
"Igreja Presbiteriana de Pinheiros","pinheiros-sao-paulo","Presbyterian","presbyterian","Brazil","Sao Paulo","Pinheiros, Sao Paulo, Brazil","Pastor Arival Dias Casimiro","[https://ippinheiros.org.br](https://ippinheiros.org.br)","+55 11 3815 1313","secretaria@ippinheiros.org.br","A traditional yet dynamic Presbyterian church in the heart of Sao Paulo.","Reformed and always reforming.","1906","5000","15","false","true","true",null
"Nairobi Chapel Ngong Road","nairobi-chapel-nairobi","Evangelical","evangelical","Kenya","Nairobi","Ngong Rd, Nairobi, Kenya","Pastor Oscar Muriu","[https://nairobichapel.org](https://nairobichapel.org)","+254 700 000 000","info@nairobichapel.org","A vibrant, multi-generational church in Nairobi focused on community transformation.","Growing D.E.E.P. to reach W.I.D.E.","1952","5000","12","false","true","true",null
"Watoto Church Kampala","watoto-kampala","Pentecostal","pentecostal","Uganda","Kampala","Kampala, Uganda","Pastor Gary Skinner","[https://watotochurch.com](https://watotochurch.com)","+256 000 0000","info@watoto.org","Formerly Kampala Pentecostal Church, famous for its children's choir and orphan care.","Rescue, raise, rebuild.","1984","25000","20","false","true","true",null
"House on the Rock Lagos","hotr-lagos-lagos","Pentecostal","pentecostal","Nigeria","Lagos","Lekki, Lagos, Nigeria","Pastor Paul Adefarasin","[https://houseontherock.org.ng](https://houseontherock.org.ng)","+234 1 000 0000","info@hotr.org.ng","A vibrant charismatic church known for hosting 'The Experience' gospel concert.","Building a people of destiny.","1994","15000","15","false","true","true",null
"Covenant Christian Centre Lagos","covenant-lagos-lagos","Charismatic","charismatic","Nigeria","Lagos","Iganmu, Lagos, Nigeria","Pastor Poju Oyemade","[https://insightsforliving.org](https://insightsforliving.org)","+234 1 000 0000","info@insights.org.ng","A contemporary church in Lagos focused on faith and professional excellence.","Equipping believers for society.","1994","12000","10","false","true","true",null
"Jesus Is Lord Church Manila","jil-manila-manila","Pentecostal","pentecostal","Philippines","Manila","Manila, Philippines","Bishop Eddie Villanueva","[https://jilworldwide.org](https://jilworldwide.org)","+63 2 000 0000","info@jil.org","A massive international Pentecostal movement originating in the Philippines.","Serving the nations.","1978","1,000,000","50","false","true","true",null
"C3 Church Sydney","c3-sydney-sydney","Pentecostal","pentecostal","Australia","Sydney","Oxford Falls, Sydney, Australia","Pastor Phil Pringle","[https://c3churchglobal.com](https://c3churchglobal.com)","+61 2 000 0000","info@c3.org","The founding church of the C3 global movement, focused on creative expression.","To reach the world for Christ.","1980","6000","12","false","true","true",null`;

function parseCSVLine(line: string) {
    const result: string[] = [];
    let cur = '';
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
        const char = line[i];
        if (char === '"') {
            inQuotes = !inQuotes;
        } else if (char === ',' && !inQuotes) {
            result.push(cur.trim());
            cur = '';
        } else {
            cur += char;
        }
    }
    result.push(cur.trim());
    return result;
}

function cleanMarkdownLink(val: string | null) {
    if (!val) return val;
    // Match [text](url) and return url
    const match = val.match(/\[.*?\]\((.*?)\)/);
    if (match && match[1]) {
        return match[1];
    }
    return val;
}

async function main() {
    const lines = csvData.split('\n');
    const headers = parseCSVLine(lines[0]);
    const data = lines.slice(1).filter(l => l.trim()).map(line => {
        const values = parseCSVLine(line);
        const obj: any = {};
        headers.forEach((h, i) => {
            let val: any = values[i];
            if (val === 'null' || val === '' || val === undefined) val = null;
            
            // Clean markdown links for website and donation_url
            if (h === 'website' || h === 'donation_url') {
                val = cleanMarkdownLink(val);
            }

            if (val === 'true') val = true;
            if (val === 'false') val = false;
            
            // Numbers
            if (['founding_year', 'member_count', 'ministry_count'].includes(h)) {
                if (typeof val === 'string') {
                    // Remove commas and stuff for large numbers like "90,000"
                    val = val.replace(/,/g, '');
                }
                val = parseInt(val) || 0;
            }
            obj[h] = val;
        });
        return obj;
    });

    console.log(`Prepared ${data.length} new churches for insertion.`);

    // Chunking to avoid large request payload
    const chunkSize = 50;
    for (let i = 0; i < data.length; i += chunkSize) {
        const chunk = data.slice(i, i + chunkSize);
        const { error } = await supabase
            .from('church_registry')
            .upsert(chunk, { onConflict: 'slug' });
        
        if (error) {
            console.error(`Error inserting chunk ${i / chunkSize}:`, error);
        } else {
            console.log(`Successfully inserted chunk ${i / chunkSize + 1}`);
        }
    }

    const { count } = await supabase
        .from('church_registry')
        .select('*', { count: 'exact', head: true });

    console.log(`Seeding complete. Total churches in database: ${count}`);
}

main().catch(console.error);
